/**
 * Canonical ingredient price catalog for recipe cost estimation.
 *
 * Each entry collapses many raw ingredient-name variants (e.g. "ajo",
 * "ajo picado", "dientes de ajo") into one priced ingredient. `priceCOP`
 * is real, sourced data (see `source`/`sourceDate`) wherever possible --
 * entries still at 0 haven't been researched yet and must not be used to
 * compute a cost until filled in (see scripts/compute-recipe-costs.ts,
 * which refuses to run while any matched ingredient has priceCOP === 0).
 *
 * `matchKeywords` are lowercase substrings checked against raw recipe
 * ingredient names. Matching picks the *longest* keyword match across the
 * whole catalog, so more specific entries (e.g. "cebolla morada") win over
 * generic ones (e.g. "cebolla") when both would otherwise match.
 */

export type PriceUnit =
  | "kg"
  | "l"
  | "unidad"
  | "docena"
  | "atado"
  | "paquete"
  | "lata"
  | "caja"
  | "botella";

export type IngredientPrice = {
  id: string;
  name: string;
  category: string;
  matchKeywords: string[];
  /** Price in COP for one `unit`. 0 = not yet researched. */
  priceCOP: number;
  unit: PriceUnit;
  /**
   * Average weight in grams for one count-unit ("unidad", "diente", etc.)
   * of this ingredient, when the recipe measures it by count but this
   * catalog prices it by kg. Standard culinary reference weight, not a
   * financial figure -- doesn't need a market source.
   */
  avgUnitWeightG?: number;
  source: string;
  sourceDate: string;
};

export const INGREDIENT_CATALOG: IngredientPrice[] = [
  // ---- Aceites y grasas ----
  {
    id: "aceite-oliva",
    name: "Aceite de oliva",
    category: "Aceites y grasas",
    matchKeywords: ["aceite de oliva"],
    priceCOP: 0,
    unit: "l",
    source: "",
    sourceDate: "",
  },
  {
    id: "aceite-vegetal",
    name: "Aceite vegetal",
    category: "Aceites y grasas",
    matchKeywords: ["aceite vegetal"],
    priceCOP: 0,
    unit: "l",
    source: "",
    sourceDate: "",
  },
  {
    id: "aceite-ajonjoli",
    name: "Aceite de ajonjolí / sésamo",
    category: "Aceites y grasas",
    matchKeywords: ["aceite de ajonjolí", "aceite de sésamo", "aceite de sesamo"],
    priceCOP: 0,
    unit: "l",
    source: "",
    sourceDate: "",
  },
  {
    id: "aceite-coco",
    name: "Aceite de coco",
    category: "Aceites y grasas",
    matchKeywords: ["aceite de coco"],
    priceCOP: 0,
    unit: "l",
    source: "",
    sourceDate: "",
  },
  {
    id: "mantequilla",
    name: "Mantequilla",
    category: "Aceites y grasas",
    matchKeywords: ["mantequilla"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },

  // ---- Especias secas ----
  {
    id: "comino",
    name: "Comino molido",
    category: "Especias secas",
    matchKeywords: ["comino"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "canela",
    name: "Canela en polvo",
    category: "Especias secas",
    matchKeywords: ["canela"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "pimenton-polvo",
    name: "Pimentón / paprika en polvo",
    category: "Especias secas",
    matchKeywords: ["pimentón dulce", "pimenton dulce", "pimentón ahumado", "pimenton ahumado", "pimentón picante en polvo", "pimentón dulce ahumado", "pimentón en polvo"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "oregano-seco",
    name: "Orégano seco",
    category: "Especias secas",
    matchKeywords: ["orégano seco", "oregano seco", "orégano"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "curcuma",
    name: "Cúrcuma molida",
    category: "Especias secas",
    matchKeywords: ["cúrcuma", "curcuma"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "curry-polvo",
    name: "Curry en polvo",
    category: "Especias secas",
    matchKeywords: ["curry en polvo", "curry"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "chile-polvo",
    name: "Chile en polvo",
    category: "Especias secas",
    matchKeywords: ["chile en polvo", "chile guajillo en polvo"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "cilantro-molido",
    name: "Cilantro molido (especia)",
    category: "Especias secas",
    matchKeywords: ["cilantro molido"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "jengibre-molido",
    name: "Jengibre molido",
    category: "Especias secas",
    matchKeywords: ["jengibre molido"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "tomillo-seco",
    name: "Tomillo seco",
    category: "Especias secas",
    matchKeywords: ["tomillo seco", "tomillo fresco (u orégano seco)", "tomillo fresco o seco", "tomillo fresco"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "laurel",
    name: "Laurel (hoja seca)",
    category: "Especias secas",
    matchKeywords: ["laurel"],
    priceCOP: 0,
    unit: "paquete",
    source: "",
    sourceDate: "",
  },
  {
    id: "ajo-polvo",
    name: "Ajo en polvo",
    category: "Especias secas",
    matchKeywords: ["ajo en polvo"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "cebolla-polvo",
    name: "Cebolla en polvo",
    category: "Especias secas",
    matchKeywords: ["cebolla en polvo"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "pimienta-cayena",
    name: "Pimienta cayena",
    category: "Especias secas",
    matchKeywords: ["pimienta cayena"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "azafran",
    name: "Azafrán (hebras)",
    category: "Especias secas",
    matchKeywords: ["azafrán", "azafran"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "chile-escamas",
    name: "Escamas de chile rojo",
    category: "Especias secas",
    matchKeywords: ["escamas de chile"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "sal",
    name: "Sal",
    category: "Especias secas",
    matchKeywords: ["sal al gusto", "sal marina", "sal,"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "pimienta-negra",
    name: "Pimienta negra",
    category: "Especias secas",
    matchKeywords: ["pimienta negra", "pimienta al gusto", "pimienta molida"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },

  // ---- Hierbas frescas ----
  {
    id: "cilantro-fresco",
    name: "Cilantro fresco",
    category: "Hierbas frescas",
    matchKeywords: ["cilantro fresco", "cilantro o menta fresca", "cilantro o perejil fresco"],
    priceCOP: 0,
    unit: "atado",
    source: "",
    sourceDate: "",
  },
  {
    id: "perejil-fresco",
    name: "Perejil fresco",
    category: "Hierbas frescas",
    matchKeywords: ["perejil fresco", "perejil o cilantro fresco"],
    priceCOP: 0,
    unit: "atado",
    source: "",
    sourceDate: "",
  },
  {
    id: "albahaca",
    name: "Albahaca fresca",
    category: "Hierbas frescas",
    matchKeywords: ["albahaca"],
    priceCOP: 0,
    unit: "atado",
    source: "",
    sourceDate: "",
  },
  {
    id: "menta",
    name: "Menta / hierbabuena fresca",
    category: "Hierbas frescas",
    matchKeywords: ["menta fresca", "hierbabuena"],
    priceCOP: 0,
    unit: "atado",
    source: "",
    sourceDate: "",
  },
  {
    id: "eneldo",
    name: "Eneldo fresco",
    category: "Hierbas frescas",
    matchKeywords: ["eneldo"],
    priceCOP: 0,
    unit: "atado",
    source: "",
    sourceDate: "",
  },
  {
    id: "romero",
    name: "Romero fresco",
    category: "Hierbas frescas",
    matchKeywords: ["romero"],
    priceCOP: 0,
    unit: "atado",
    source: "",
    sourceDate: "",
  },
  {
    id: "cebollin",
    name: "Cebollín / cebolla larga",
    category: "Hierbas frescas",
    matchKeywords: ["cebolla larga", "cebollín", "cebollin"],
    priceCOP: 0,
    unit: "atado",
    source: "",
    sourceDate: "",
  },

  // ---- Vegetales y tubérculos ----
  {
    id: "cebolla-blanca",
    name: "Cebolla cabezona blanca",
    category: "Vegetales y tubérculos",
    matchKeywords: ["cebolla, ", "cebolla picada", "cebolla en trozos", "cebolla rallada", "cebolla cabezona", "cebolla en tiras", "cebolla"],
    priceCOP: 0,
    unit: "kg",
    avgUnitWeightG: 150,
    source: "",
    sourceDate: "",
  },
  {
    id: "cebolla-morada",
    name: "Cebolla morada",
    category: "Vegetales y tubérculos",
    matchKeywords: ["cebolla morada"],
    priceCOP: 0,
    unit: "kg",
    avgUnitWeightG: 120,
    source: "",
    sourceDate: "",
  },
  {
    id: "ajo",
    name: "Ajo",
    category: "Vegetales y tubérculos",
    matchKeywords: ["ajo picado", "ajo, picado", "dientes de ajo", "ajo rallado", "ajo en láminas", "ajo, un diente", "diente de ajo", "ajo,", "ajo"],
    priceCOP: 0,
    unit: "kg",
    avgUnitWeightG: 5,
    source: "",
    sourceDate: "",
  },
  {
    id: "tomate-maduro",
    name: "Tomate maduro (chonto)",
    category: "Vegetales y tubérculos",
    matchKeywords: ["tomate maduro", "tomates maduros", "tomate picado", "tomate en cubos", "tomate triturado", "tomate, en cubos", "tomate rallado"],
    priceCOP: 0,
    unit: "kg",
    avgUnitWeightG: 120,
    source: "",
    sourceDate: "",
  },
  {
    id: "tomate-cherry",
    name: "Tomate cherry",
    category: "Vegetales y tubérculos",
    matchKeywords: ["tomate cherry", "tomates cherry"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "pimenton-rojo",
    name: "Pimentón rojo",
    category: "Vegetales y tubérculos",
    matchKeywords: ["pimentón rojo", "pimiento rojo"],
    priceCOP: 0,
    unit: "kg",
    avgUnitWeightG: 150,
    source: "",
    sourceDate: "",
  },
  {
    id: "pimenton-verde",
    name: "Pimentón verde",
    category: "Vegetales y tubérculos",
    matchKeywords: ["pimiento verde"],
    priceCOP: 0,
    unit: "kg",
    avgUnitWeightG: 150,
    source: "",
    sourceDate: "",
  },
  {
    id: "pimenton-amarillo",
    name: "Pimentón amarillo",
    category: "Vegetales y tubérculos",
    matchKeywords: ["pimentón amarillo"],
    priceCOP: 0,
    unit: "kg",
    avgUnitWeightG: 150,
    source: "",
    sourceDate: "",
  },
  {
    id: "zanahoria",
    name: "Zanahoria",
    category: "Vegetales y tubérculos",
    matchKeywords: ["zanahoria"],
    priceCOP: 0,
    unit: "kg",
    avgUnitWeightG: 80,
    source: "",
    sourceDate: "",
  },
  {
    id: "calabacin",
    name: "Calabacín (zucchini)",
    category: "Vegetales y tubérculos",
    matchKeywords: ["calabacín", "calabacin"],
    priceCOP: 0,
    unit: "kg",
    avgUnitWeightG: 200,
    source: "",
    sourceDate: "",
  },
  {
    id: "pepino",
    name: "Pepino",
    category: "Vegetales y tubérculos",
    matchKeywords: ["pepino"],
    priceCOP: 0,
    unit: "kg",
    avgUnitWeightG: 300,
    source: "",
    sourceDate: "",
  },
  {
    id: "apio",
    name: "Apio",
    category: "Vegetales y tubérculos",
    matchKeywords: ["apio"],
    priceCOP: 0,
    unit: "kg",
    avgUnitWeightG: 60,
    source: "",
    sourceDate: "",
  },
  {
    id: "brocoli",
    name: "Brócoli",
    category: "Vegetales y tubérculos",
    matchKeywords: ["brócoli", "brocoli"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "coliflor",
    name: "Coliflor",
    category: "Vegetales y tubérculos",
    matchKeywords: ["coliflor"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "espinaca",
    name: "Espinaca",
    category: "Vegetales y tubérculos",
    matchKeywords: ["espinaca"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "col-morada",
    name: "Col morada (repollo morado)",
    category: "Vegetales y tubérculos",
    matchKeywords: ["col morada"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "col-blanca",
    name: "Col blanca (repollo)",
    category: "Vegetales y tubérculos",
    matchKeywords: ["col blanca"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "kale",
    name: "Col rizada (kale)",
    category: "Vegetales y tubérculos",
    matchKeywords: ["col rizada", "kale"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "repollo-chino",
    name: "Repollo chino (napa)",
    category: "Vegetales y tubérculos",
    matchKeywords: ["repollo chino", "napa"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "lechuga",
    name: "Lechuga (crespa o romana)",
    category: "Vegetales y tubérculos",
    matchKeywords: ["lechuga"],
    priceCOP: 0,
    unit: "unidad",
    source: "",
    sourceDate: "",
  },
  {
    id: "champinones",
    name: "Champiñones",
    category: "Vegetales y tubérculos",
    matchKeywords: ["champiñones grandes", "champiñones", "champinones"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "champinones-shiitake",
    name: "Champiñones shiitake",
    category: "Vegetales y tubérculos",
    matchKeywords: ["shiitake"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "berenjena",
    name: "Berenjena",
    category: "Vegetales y tubérculos",
    matchKeywords: ["berenjena"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "puerro",
    name: "Puerro",
    category: "Vegetales y tubérculos",
    matchKeywords: ["puerro"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "ejotes",
    name: "Ejotes / habichuelas",
    category: "Vegetales y tubérculos",
    matchKeywords: ["ejotes", "habichuelas"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "arveja-verde",
    name: "Arveja verde",
    category: "Vegetales y tubérculos",
    matchKeywords: ["arveja verde", "arvejas verdes"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "mazorca",
    name: "Mazorca / granos de maíz tierno",
    category: "Vegetales y tubérculos",
    matchKeywords: ["granos de mazorca", "mazorca", "granos de elote"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "papa",
    name: "Papa (pastusa o sabanera)",
    category: "Vegetales y tubérculos",
    matchKeywords: ["papa sabanera", "papa,", "papa pequeña", "papa mediana"],
    priceCOP: 0,
    unit: "kg",
    avgUnitWeightG: 150,
    source: "",
    sourceDate: "",
  },
  {
    id: "papa-criolla",
    name: "Papa criolla",
    category: "Vegetales y tubérculos",
    matchKeywords: ["papa criolla"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "camote",
    name: "Camote / batata",
    category: "Vegetales y tubérculos",
    matchKeywords: ["camote", "batata"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "calabaza",
    name: "Calabaza / auyama",
    category: "Vegetales y tubérculos",
    matchKeywords: ["calabaza", "auyama"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "aguacate",
    name: "Aguacate",
    category: "Vegetales y tubérculos",
    matchKeywords: ["aguacate"],
    priceCOP: 0,
    unit: "unidad",
    avgUnitWeightG: 200,
    source: "",
    sourceDate: "",
  },
  {
    id: "jengibre-fresco",
    name: "Jengibre fresco",
    category: "Vegetales y tubérculos",
    matchKeywords: ["jengibre fresco"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "chile-jalapeno",
    name: "Chile jalapeño",
    category: "Vegetales y tubérculos",
    matchKeywords: ["jalapeño", "jalapeno"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "aji-picante",
    name: "Ají picante fresco",
    category: "Vegetales y tubérculos",
    matchKeywords: ["ají picante", "ají o chile", "chile o ají"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "edamame",
    name: "Edamame",
    category: "Vegetales y tubérculos",
    matchKeywords: ["edamame"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "bok-choy",
    name: "Bok choy",
    category: "Vegetales y tubérculos",
    matchKeywords: ["bok choy"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "esparragos",
    name: "Espárragos",
    category: "Vegetales y tubérculos",
    matchKeywords: ["espárragos", "esparragos"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "agua",
    name: "Agua",
    category: "Vegetales y tubérculos",
    matchKeywords: ["agua fría", "agua tibia", "agua (para", "agua,", "agua ", "agua"],
    priceCOP: 1,
    unit: "l",
    source: "Agua de acueducto -- costo no aplicable a efectos prácticos.",
    sourceDate: "2026-07-17",
  },

  // ---- Frutas ----
  {
    id: "limon",
    name: "Limón (Tahití)",
    category: "Frutas",
    matchKeywords: ["jugo de limón", "jugo de limon", "ralladura de limón", "limón,", "limón en", "limón ", "limón"],
    priceCOP: 0,
    unit: "kg",
    avgUnitWeightG: 90,
    source: "",
    sourceDate: "",
  },
  {
    id: "lima",
    name: "Lima",
    category: "Frutas",
    matchKeywords: ["lima,", "lima "],
    priceCOP: 0,
    unit: "kg",
    avgUnitWeightG: 60,
    source: "",
    sourceDate: "",
  },
  {
    id: "naranja",
    name: "Naranja",
    category: "Frutas",
    matchKeywords: ["naranja", "jugo de naranja"],
    priceCOP: 0,
    unit: "kg",
    avgUnitWeightG: 200,
    source: "",
    sourceDate: "",
  },
  {
    id: "manzana-verde",
    name: "Manzana verde",
    category: "Frutas",
    matchKeywords: ["manzana verde", "manzanas", "manzana "],
    priceCOP: 0,
    unit: "kg",
    avgUnitWeightG: 150,
    source: "",
    sourceDate: "",
  },
  {
    id: "platano-maduro",
    name: "Plátano maduro",
    category: "Frutas",
    matchKeywords: ["plátano maduro", "platano maduro"],
    priceCOP: 0,
    unit: "kg",
    avgUnitWeightG: 150,
    source: "",
    sourceDate: "",
  },
  {
    id: "banano",
    name: "Banano",
    category: "Frutas",
    matchKeywords: ["banano"],
    priceCOP: 0,
    unit: "kg",
    avgUnitWeightG: 120,
    source: "",
    sourceDate: "",
  },
  {
    id: "mango",
    name: "Mango maduro",
    category: "Frutas",
    matchKeywords: ["mango maduro", "mango,"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "pina",
    name: "Piña fresca",
    category: "Frutas",
    matchKeywords: ["piña fresca", "pina fresca"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "peras",
    name: "Peras",
    category: "Frutas",
    matchKeywords: ["peras maduras", "peras"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "frutos-rojos",
    name: "Frutos rojos mixtos",
    category: "Frutas",
    matchKeywords: ["frutos rojos"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },

  // ---- Proteínas: carnes, pescados, huevo ----
  {
    id: "pechuga-pollo",
    name: "Pechuga de pollo",
    category: "Proteínas",
    matchKeywords: ["pechuga de pollo", "pechugas de pollo"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "muslos-pollo",
    name: "Muslos / contramuslos de pollo",
    category: "Proteínas",
    matchKeywords: ["muslos de pollo", "muslos y contramuslos"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "alitas-pollo",
    name: "Alitas de pollo",
    category: "Proteínas",
    matchKeywords: ["alitas de pollo"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "pollo-hueso",
    name: "Pollo con hueso",
    category: "Proteínas",
    matchKeywords: ["piezas de pollo con hueso"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "pechuga-pavo",
    name: "Pechuga de pavo",
    category: "Proteínas",
    matchKeywords: ["pechuga de pavo", "filete de pechuga de pavo"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "pavo-molido",
    name: "Pavo molido",
    category: "Proteínas",
    matchKeywords: ["pavo molido"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "carne-molida",
    name: "Carne de res molida",
    category: "Proteínas",
    matchKeywords: ["carne de res molida"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "lomo-res",
    name: "Lomo de res",
    category: "Proteínas",
    matchKeywords: ["lomo de res"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "bistec-res",
    name: "Bistec de res",
    category: "Proteínas",
    matchKeywords: ["bistec de res"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "punta-anca",
    name: "Punta de anca / falda de res",
    category: "Proteínas",
    matchKeywords: ["punta de anca", "falda de res"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "carne-estofado",
    name: "Carne de res para estofado",
    category: "Proteínas",
    matchKeywords: ["carne de res para estofado"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "lomo-cerdo",
    name: "Lomo de cerdo",
    category: "Proteínas",
    matchKeywords: ["lomo de cerdo"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "pescado-blanco",
    name: "Filete de pescado blanco",
    category: "Proteínas",
    matchKeywords: [
      "filete de tilapia",
      "filete de merluza",
      "lomo de bacalao",
      "filete de pescado blanco",
      "filete de mero",
      "filete de corvina",
      "filete de pescado firme",
      "pescado blanco fresco",
    ],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "salmon",
    name: "Filete de salmón",
    category: "Proteínas",
    matchKeywords: ["filete de salmón", "filete de salmon"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "trucha",
    name: "Filete de trucha",
    category: "Proteínas",
    matchKeywords: ["filete de trucha"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "atun-fresco",
    name: "Atún fresco (lomo)",
    category: "Proteínas",
    matchKeywords: ["lomo de atún fresco", "lomo de atun fresco"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "atun-lata",
    name: "Atún enlatado en agua",
    category: "Proteínas",
    matchKeywords: ["atún en agua", "atun en agua"],
    priceCOP: 0,
    unit: "lata",
    source: "",
    sourceDate: "",
  },
  {
    id: "camaron",
    name: "Camarón",
    category: "Proteínas",
    matchKeywords: ["camarón", "camarones", "camaron"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "mejillones",
    name: "Mejillones",
    category: "Proteínas",
    matchKeywords: ["mejillones"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "pulpo",
    name: "Pulpo cocido",
    category: "Proteínas",
    matchKeywords: ["pulpo cocido"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "huevo",
    name: "Huevo",
    category: "Proteínas",
    matchKeywords: ["huevo", "huevos", "claras de huevo"],
    priceCOP: 0,
    unit: "docena",
    avgUnitWeightG: 55,
    source: "",
    sourceDate: "",
  },
  {
    id: "tofu",
    name: "Tofu firme",
    category: "Proteínas",
    matchKeywords: ["tofu firme", "tofu,"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "tempeh",
    name: "Tempeh",
    category: "Proteínas",
    matchKeywords: ["tempeh"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "garbanzos",
    name: "Garbanzos",
    category: "Proteínas",
    matchKeywords: ["garbanzos", "garbanzo cocido"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "lentejas",
    name: "Lentejas",
    category: "Proteínas",
    matchKeywords: ["lentejas"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "frijoles",
    name: "Frijoles",
    category: "Proteínas",
    matchKeywords: ["frijoles negros", "frijoles rojos", "frijol blanco", "frijol negro"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "queso-parmesano",
    name: "Queso parmesano",
    category: "Proteínas",
    matchKeywords: ["parmesano"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "queso-feta",
    name: "Queso feta",
    category: "Proteínas",
    matchKeywords: ["queso feta"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "queso-fresco",
    name: "Queso fresco / campesino",
    category: "Proteínas",
    matchKeywords: ["queso fresco"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "queso-crema",
    name: "Queso crema",
    category: "Proteínas",
    matchKeywords: ["queso crema"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "mascarpone",
    name: "Queso mascarpone",
    category: "Proteínas",
    matchKeywords: ["mascarpone"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "queso-cabra",
    name: "Queso de cabra",
    category: "Proteínas",
    matchKeywords: ["queso de cabra"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "yogur-griego",
    name: "Yogur griego natural",
    category: "Proteínas",
    matchKeywords: ["yogur griego"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "yogur-natural",
    name: "Yogur natural",
    category: "Proteínas",
    matchKeywords: ["yogur natural"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "leche-entera",
    name: "Leche entera",
    category: "Proteínas",
    matchKeywords: ["leche entera", "leche (vegetal o entera)", "leche vegetal o entera"],
    priceCOP: 0,
    unit: "l",
    source: "",
    sourceDate: "",
  },
  {
    id: "leche-vegetal",
    name: "Leche vegetal",
    category: "Proteínas",
    matchKeywords: ["leche vegetal", "leche de almendra", "leche de avena"],
    priceCOP: 0,
    unit: "l",
    source: "",
    sourceDate: "",
  },
  {
    id: "leche-descremada",
    name: "Leche descremada",
    category: "Proteínas",
    matchKeywords: ["leche descremada"],
    priceCOP: 0,
    unit: "l",
    source: "",
    sourceDate: "",
  },
  {
    id: "leche-coco",
    name: "Leche de coco",
    category: "Proteínas",
    matchKeywords: ["leche de coco"],
    priceCOP: 0,
    unit: "lata",
    source: "",
    sourceDate: "",
  },

  // ---- Granos, cereales, harinas y panes ----
  {
    id: "arroz-blanco",
    name: "Arroz blanco",
    category: "Granos y harinas",
    matchKeywords: ["arroz blanco"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "arroz-integral",
    name: "Arroz integral",
    category: "Granos y harinas",
    matchKeywords: ["arroz integral", "arroz de grano corto"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "arroz-basmati",
    name: "Arroz basmati",
    category: "Granos y harinas",
    matchKeywords: ["arroz basmati"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "arroz-jazmin",
    name: "Arroz jazmín",
    category: "Granos y harinas",
    matchKeywords: ["arroz jazmín", "arroz jazmin"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "quinoa",
    name: "Quinoa",
    category: "Granos y harinas",
    matchKeywords: ["quinoa"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "avena",
    name: "Avena en hojuelas",
    category: "Granos y harinas",
    matchKeywords: ["avena en hojuelas", "harina de avena"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "cuscus",
    name: "Cuscús integral",
    category: "Granos y harinas",
    matchKeywords: ["cuscús", "cuscus"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "pasta-integral",
    name: "Pasta integral",
    category: "Granos y harinas",
    matchKeywords: ["pasta integral", "espagueti integral"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "harina-trigo",
    name: "Harina de trigo",
    category: "Granos y harinas",
    matchKeywords: ["harina de trigo", "harina integral de trigo"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "harina-almendra",
    name: "Harina de almendra",
    category: "Granos y harinas",
    matchKeywords: ["harina de almendra"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "harina-garbanzo",
    name: "Harina de garbanzo",
    category: "Granos y harinas",
    matchKeywords: ["harina de garbanzo"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "pan-integral",
    name: "Pan integral tajado",
    category: "Granos y harinas",
    matchKeywords: ["pan integral"],
    priceCOP: 0,
    unit: "paquete",
    source: "",
    sourceDate: "",
  },
  {
    id: "pan-rallado",
    name: "Pan rallado",
    category: "Granos y harinas",
    matchKeywords: ["pan rallado"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "tortillas-maiz",
    name: "Tortillas de maíz",
    category: "Granos y harinas",
    matchKeywords: ["tortillas de maíz", "tortillas de maiz"],
    priceCOP: 0,
    unit: "paquete",
    source: "",
    sourceDate: "",
  },
  {
    id: "tortillas-integrales",
    name: "Tortillas integrales",
    category: "Granos y harinas",
    matchKeywords: ["tortillas integrales"],
    priceCOP: 0,
    unit: "paquete",
    source: "",
    sourceDate: "",
  },
  {
    id: "papel-arroz",
    name: "Papel de arroz",
    category: "Granos y harinas",
    matchKeywords: ["papel de arroz"],
    priceCOP: 0,
    unit: "paquete",
    source: "",
    sourceDate: "",
  },
  {
    id: "fideos-arroz",
    name: "Fideos de arroz",
    category: "Granos y harinas",
    matchKeywords: ["fideos de arroz"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "galletas-integrales",
    name: "Galletas integrales",
    category: "Granos y harinas",
    matchKeywords: ["galletas integrales"],
    priceCOP: 0,
    unit: "paquete",
    source: "",
    sourceDate: "",
  },
  {
    id: "bizcochos-soletilla",
    name: "Bizcochos de soletilla",
    category: "Granos y harinas",
    matchKeywords: ["bizcochos de soletilla"],
    priceCOP: 0,
    unit: "paquete",
    source: "",
    sourceDate: "",
  },

  // ---- Endulzantes y chocolate ----
  {
    id: "miel",
    name: "Miel",
    category: "Endulzantes",
    matchKeywords: ["miel"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "panela",
    name: "Panela raspada / azúcar de coco",
    category: "Endulzantes",
    matchKeywords: ["panela raspada", "azúcar de coco"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "chocolate-oscuro",
    name: "Chocolate oscuro 70%",
    category: "Endulzantes",
    matchKeywords: ["chocolate oscuro"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "cacao-polvo",
    name: "Cacao en polvo sin azúcar",
    category: "Endulzantes",
    matchKeywords: ["cacao en polvo"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "datiles",
    name: "Dátiles deshuesados",
    category: "Endulzantes",
    matchKeywords: ["dátiles", "datiles"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "pasas",
    name: "Pasas",
    category: "Endulzantes",
    matchKeywords: ["pasas"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "arandanos-deshidratados",
    name: "Arándanos deshidratados",
    category: "Endulzantes",
    matchKeywords: ["arándanos deshidratados", "arandanos deshidratados"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "azucar",
    name: "Azúcar",
    category: "Endulzantes",
    matchKeywords: ["azúcar o panela", "azúcar,", "azucar"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },

  // ---- Salsas, caldos, vinagres y encurtidos ----
  {
    id: "salsa-soya",
    name: "Salsa de soya",
    category: "Salsas y caldos",
    matchKeywords: ["salsa de soya", "tamari"],
    priceCOP: 0,
    unit: "l",
    source: "",
    sourceDate: "",
  },
  {
    id: "caldo-vegetales",
    name: "Caldo de vegetales",
    category: "Salsas y caldos",
    matchKeywords: ["caldo de vegetales"],
    priceCOP: 0,
    unit: "l",
    source: "",
    sourceDate: "",
  },
  {
    id: "caldo-pollo",
    name: "Caldo de pollo",
    category: "Salsas y caldos",
    matchKeywords: ["caldo de pollo"],
    priceCOP: 0,
    unit: "l",
    source: "",
    sourceDate: "",
  },
  {
    id: "caldo-res",
    name: "Caldo de res",
    category: "Salsas y caldos",
    matchKeywords: ["caldo de res"],
    priceCOP: 0,
    unit: "l",
    source: "",
    sourceDate: "",
  },
  {
    id: "caldo-pescado",
    name: "Caldo de pescado o mariscos",
    category: "Salsas y caldos",
    matchKeywords: ["caldo de pescado", "caldo de mariscos"],
    priceCOP: 0,
    unit: "l",
    source: "",
    sourceDate: "",
  },
  {
    id: "vino-blanco",
    name: "Vino blanco seco",
    category: "Salsas y caldos",
    matchKeywords: ["vino blanco"],
    priceCOP: 0,
    unit: "l",
    source: "",
    sourceDate: "",
  },
  {
    id: "vinagre-arroz",
    name: "Vinagre de arroz",
    category: "Salsas y caldos",
    matchKeywords: ["vinagre de arroz"],
    priceCOP: 0,
    unit: "l",
    source: "",
    sourceDate: "",
  },
  {
    id: "vinagre-tinto",
    name: "Vinagre de vino tinto",
    category: "Salsas y caldos",
    matchKeywords: ["vinagre de vino tinto"],
    priceCOP: 0,
    unit: "l",
    source: "",
    sourceDate: "",
  },
  {
    id: "vinagre-balsamico",
    name: "Vinagre balsámico",
    category: "Salsas y caldos",
    matchKeywords: ["vinagre balsámico", "vinagre balsamico"],
    priceCOP: 0,
    unit: "l",
    source: "",
    sourceDate: "",
  },
  {
    id: "vinagre-manzana",
    name: "Vinagre de manzana",
    category: "Salsas y caldos",
    matchKeywords: ["vinagre de manzana"],
    priceCOP: 0,
    unit: "l",
    source: "",
    sourceDate: "",
  },
  {
    id: "vinagre-blanco",
    name: "Vinagre blanco",
    category: "Salsas y caldos",
    matchKeywords: ["vinagre blanco", "vinagre de vino blanco"],
    priceCOP: 0,
    unit: "l",
    source: "",
    sourceDate: "",
  },
  {
    id: "mostaza-dijon",
    name: "Mostaza dijon",
    category: "Salsas y caldos",
    matchKeywords: ["mostaza dijon"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "tahini",
    name: "Tahini",
    category: "Salsas y caldos",
    matchKeywords: ["tahini"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "hummus",
    name: "Hummus",
    category: "Salsas y caldos",
    matchKeywords: ["hummus"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "salsa-pescado",
    name: "Salsa de pescado",
    category: "Salsas y caldos",
    matchKeywords: ["salsa de pescado"],
    priceCOP: 0,
    unit: "l",
    source: "",
    sourceDate: "",
  },
  {
    id: "salsa-ostion",
    name: "Salsa de ostión",
    category: "Salsas y caldos",
    matchKeywords: ["salsa de ostión", "salsa de ostion"],
    priceCOP: 0,
    unit: "l",
    source: "",
    sourceDate: "",
  },
  {
    id: "pasta-curry",
    name: "Pasta de curry",
    category: "Salsas y caldos",
    matchKeywords: ["pasta de curry"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "pasta-miso",
    name: "Pasta de miso blanco",
    category: "Salsas y caldos",
    matchKeywords: ["pasta de miso"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "alga-wakame",
    name: "Alga wakame seca",
    category: "Salsas y caldos",
    matchKeywords: ["alga wakame"],
    priceCOP: 0,
    unit: "paquete",
    source: "",
    sourceDate: "",
  },
  {
    id: "pasta-achiote",
    name: "Pasta de achiote",
    category: "Salsas y caldos",
    matchKeywords: ["pasta de achiote"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "sriracha",
    name: "Sriracha / salsa picante",
    category: "Salsas y caldos",
    matchKeywords: ["sriracha", "salsa picante"],
    priceCOP: 0,
    unit: "botella",
    source: "",
    sourceDate: "",
  },
  {
    id: "aceitunas-negras",
    name: "Aceitunas negras",
    category: "Salsas y caldos",
    matchKeywords: ["aceitunas negras"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "aceitunas-verdes",
    name: "Aceitunas verdes",
    category: "Salsas y caldos",
    matchKeywords: ["aceitunas verdes"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "alcaparras",
    name: "Alcaparras",
    category: "Salsas y caldos",
    matchKeywords: ["alcaparras"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "anchoas",
    name: "Filetes de anchoa",
    category: "Salsas y caldos",
    matchKeywords: ["anchoa"],
    priceCOP: 0,
    unit: "lata",
    source: "",
    sourceDate: "",
  },
  {
    id: "palmitos",
    name: "Palmitos en conserva",
    category: "Salsas y caldos",
    matchKeywords: ["palmitos"],
    priceCOP: 0,
    unit: "lata",
    source: "",
    sourceDate: "",
  },
  {
    id: "tomate-lata",
    name: "Tomate triturado enlatado",
    category: "Salsas y caldos",
    matchKeywords: ["tomate en cubos (enlatado", "tomate triturado (lata)", "pasta de tomate"],
    priceCOP: 0,
    unit: "lata",
    source: "",
    sourceDate: "",
  },

  // ---- Frutos secos y semillas ----
  {
    id: "nueces",
    name: "Nueces",
    category: "Frutos secos y semillas",
    matchKeywords: ["nueces", "frutos secos picados"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "almendras",
    name: "Almendras",
    category: "Frutos secos y semillas",
    matchKeywords: ["almendras"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "mani-tostado",
    name: "Maní tostado",
    category: "Frutos secos y semillas",
    matchKeywords: ["maní tostado", "mani tostado"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "mantequilla-mani",
    name: "Mantequilla de maní",
    category: "Frutos secos y semillas",
    matchKeywords: ["mantequilla de maní", "mantequilla de mani"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "ajonjoli",
    name: "Semillas de ajonjolí / sésamo",
    category: "Frutos secos y semillas",
    matchKeywords: ["ajonjolí", "ajonjoli", "semillas de sésamo", "semillas de sesamo"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "chia",
    name: "Semillas de chía",
    category: "Frutos secos y semillas",
    matchKeywords: ["semillas de chía", "semillas de chia"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "girasol",
    name: "Semillas de girasol",
    category: "Frutos secos y semillas",
    matchKeywords: ["semillas de girasol"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "semillas-calabaza",
    name: "Semillas de calabaza tostadas",
    category: "Frutos secos y semillas",
    matchKeywords: ["semillas de calabaza"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },

  // ---- Despensa y otros ----
  {
    id: "gelatina-sin-sabor",
    name: "Gelatina sin sabor en polvo",
    category: "Despensa y otros",
    matchKeywords: ["gelatina sin sabor"],
    priceCOP: 0,
    unit: "caja",
    source: "",
    sourceDate: "",
  },
  {
    id: "polvo-hornear",
    name: "Polvo de hornear",
    category: "Despensa y otros",
    matchKeywords: ["polvo de hornear"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "bicarbonato",
    name: "Bicarbonato de sodio",
    category: "Despensa y otros",
    matchKeywords: ["bicarbonato de sodio"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "maicena",
    name: "Maicena / fécula de maíz",
    category: "Despensa y otros",
    matchKeywords: ["maicena", "fécula de maíz", "fecula de maiz"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "cafe-instantaneo",
    name: "Café instantáneo",
    category: "Despensa y otros",
    matchKeywords: ["café instantáneo", "cafe instantaneo"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "cafe-espresso",
    name: "Café espresso",
    category: "Despensa y otros",
    matchKeywords: ["café espresso", "cafe espresso"],
    priceCOP: 0,
    unit: "kg",
    source: "",
    sourceDate: "",
  },
  {
    id: "esencia-vainilla",
    name: "Esencia de vainilla",
    category: "Despensa y otros",
    matchKeywords: ["esencia de vainilla"],
    priceCOP: 0,
    unit: "botella",
    source: "",
    sourceDate: "",
  },
];
