/**
 * Canonical ingredient price catalog for recipe cost estimation.
 *
 * Each entry collapses many raw ingredient-name variants (e.g. "ajo",
 * "ajo picado", "dientes de ajo") into one priced ingredient. `priceCOP`
 * is real, sourced data (see `source`/`sourceDate`) wherever possible --
 * entries still at 0 haven't been researched yet and must not be used to
 * compute a cost until filled in (see scripts/compute-recipe-costs.ts,
 * which refuses to run while any matched ingredient has priceCOP === 0).
 *
 * `matchKeywords` are lowercase substrings checked against raw recipe
 * ingredient names. Matching picks the *longest* keyword match across the
 * whole catalog, so more specific entries (e.g. "cebolla morada") win over
 * generic ones (e.g. "cebolla") when both would otherwise match.
 */

export type PriceUnit =
  | "kg"
  | "l"
  | "unidad"
  | "docena"
  | "atado"
  | "paquete"
  | "lata"
  | "caja"
  | "botella";

export type IngredientPrice = {
  id: string;
  name: string;
  category: string;
  matchKeywords: string[];
  /** Price in COP for one `unit`. 0 = not yet researched. */
  priceCOP: number;
  unit: PriceUnit;
  /**
   * Average weight in grams for one count-unit ("unidad", "diente", etc.)
   * of this ingredient, when the recipe measures it by count but this
   * catalog prices it by kg. Standard culinary reference weight, not a
   * financial figure -- doesn't need a market source.
   */
  avgUnitWeightG?: number;
  /** For unit: "paquete" -- how many count-units (slices, tortillas...) one package holds. */
  packageUnitCount?: number;
  /** For unit: "paquete" -- typical package weight in grams, for gram-measured ingredients. */
  packageSizeG?: number;
  /** For unit: "lata"/"botella" -- typical container volume in ml, for ml-measured liquids. */
  packageSizeMl?: number;
  /** Chopped fresh herb is much less dense than a powder -- changes the cda/cdta/taza-to-grams conversion. */
  isFreshHerb?: boolean;
  source: string;
  sourceDate: string;
};

export const INGREDIENT_CATALOG: IngredientPrice[] = [
  // ---- Aceites y grasas ----
  {
    id: "aceite-oliva",
    name: "Aceite de oliva",
    category: "Aceites y grasas",
    matchKeywords: ["aceite de oliva"],
    priceCOP: 32450,
    unit: "l",
    source: "Éxito.com, Aceite de oliva Frescampo extra virgen (1000 ml)",
    sourceDate: "2026-07-17",
  },
  {
    id: "aceite-vegetal",
    name: "Aceite vegetal",
    category: "Aceites y grasas",
    matchKeywords: ["aceite vegetal"],
    priceCOP: 6950,
    unit: "l",
    source: "Éxito.com, Aceite Frescampo multiusos (3000 ml)",
    sourceDate: "2026-07-17",
  },
  {
    id: "aceite-ajonjoli",
    name: "Aceite de ajonjolí / sésamo",
    category: "Aceites y grasas",
    matchKeywords: ["aceite de ajonjolí", "aceite de sésamo", "aceite de sesamo"],
    priceCOP: 134400,
    unit: "l",
    source: "Éxito.com, Aceite Bizancio tostado (240 ml)",
    sourceDate: "2026-07-17",
  },
  {
    id: "aceite-coco",
    name: "Aceite de coco",
    category: "Aceites y grasas",
    matchKeywords: ["aceite de coco"],
    priceCOP: 178330,
    unit: "l",
    source: "Éxito.com, Aceite de coco virgen (420 ml)",
    sourceDate: "2026-07-17",
  },
  {
    id: "mantequilla",
    name: "Mantequilla",
    category: "Aceites y grasas",
    matchKeywords: ["mantequilla"],
    priceCOP: 61800,
    unit: "kg",
    source: "Éxito.com, Mantequilla Colanta sin sal esparcible (250 g)",
    sourceDate: "2026-07-17",
  },

  // ---- Especias secas ----
  {
    id: "comino",
    name: "Comino molido",
    category: "Especias secas",
    matchKeywords: ["comino"],
    priceCOP: 77090,
    unit: "kg",
    source: "Éxito.com, Comino El Rey molido (55 g)",
    sourceDate: "2026-07-17",
  },
  {
    id: "canela",
    name: "Canela en polvo",
    category: "Especias secas",
    matchKeywords: ["canela"],
    priceCOP: 322300,
    unit: "kg",
    source: "Éxito.com, Canela Badia molida (56 g)",
    sourceDate: "2026-07-17",
  },
  {
    id: "pimenton-polvo",
    name: "Pimentón / paprika en polvo",
    category: "Especias secas",
    matchKeywords: ["pimentón dulce", "pimenton dulce", "pimentón ahumado", "pimenton ahumado", "pimentón picante en polvo", "pimentón dulce ahumado", "pimentón en polvo"],
    priceCOP: 68400,
    unit: "kg",
    source: "Éxito.com, Pimentón El Rey pura (25 g)",
    sourceDate: "2026-07-17",
  },
  {
    id: "oregano-seco",
    name: "Orégano seco",
    category: "Especias secas",
    matchKeywords: ["orégano seco", "oregano seco", "orégano"],
    priceCOP: 98500,
    unit: "kg",
    source: "Éxito.com, Orégano Comarrico molido (20 g)",
    sourceDate: "2026-07-17",
  },
  {
    id: "curcuma",
    name: "Cúrcuma molida",
    category: "Especias secas",
    matchKeywords: ["cúrcuma", "curcuma"],
    priceCOP: 88400,
    unit: "kg",
    source: "Éxito.com, Cúrcuma El Rey pura (25 g)",
    sourceDate: "2026-07-17",
  },
  {
    id: "curry-polvo",
    name: "Curry en polvo",
    category: "Especias secas",
    matchKeywords: ["curry en polvo", "curry"],
    priceCOP: 193600,
    unit: "kg",
    source: "Éxito.com, Curry Badia (28 g)",
    sourceDate: "2026-07-17",
  },
  {
    id: "chile-polvo",
    name: "Chile en polvo",
    category: "Especias secas",
    matchKeywords: ["chile en polvo", "chile guajillo en polvo"],
    priceCOP: 250000,
    unit: "kg",
    source: "Estimación no verificada -- sin precio vigente para chile guajillo específico; se usa el de escamas de chile como proxy de la misma categoría",
    sourceDate: "2026-07-17",
  },
  {
    id: "cilantro-molido",
    name: "Cilantro molido (especia)",
    category: "Especias secas",
    matchKeywords: ["cilantro molido"],
    priceCOP: 897200,
    unit: "kg",
    source: "Éxito.com, Cilantro Badia en polvo (7.1 g) -- precio por kg elevado por ser un empaque muy pequeño",
    sourceDate: "2026-07-17",
  },
  {
    id: "jengibre-molido",
    name: "Jengibre molido",
    category: "Especias secas",
    matchKeywords: ["jengibre molido"],
    priceCOP: 171300,
    unit: "kg",
    source: "Éxito.com, Jengibre El Rey puro (15 g)",
    sourceDate: "2026-07-17",
  },
  {
    id: "tomillo-seco",
    name: "Tomillo seco",
    category: "Especias secas",
    matchKeywords: ["tomillo seco", "tomillo fresco (u orégano seco)", "tomillo fresco o seco", "tomillo fresco"],
    priceCOP: 115000,
    unit: "kg",
    avgUnitWeightG: 2,
    source: "Éxito.com, Tomillo Frescampo 100% natural (20 g)",
    sourceDate: "2026-07-17",
  },
  {
    id: "laurel",
    name: "Laurel (hoja seca)",
    category: "Especias secas",
    matchKeywords: ["laurel"],
    priceCOP: 2980,
    unit: "paquete",
    packageUnitCount: 25,
    source: "Éxito.com, Laurel Frescampo deshidratado (37 g)",
    sourceDate: "2026-07-17",
  },
  {
    id: "ajo-polvo",
    name: "Ajo en polvo",
    category: "Especias secas",
    matchKeywords: ["ajo en polvo"],
    priceCOP: 28400,
    unit: "kg",
    source: "Éxito.com, Ajo El Rey en polvo (55 g)",
    sourceDate: "2026-07-17",
  },
  {
    id: "cebolla-polvo",
    name: "Cebolla en polvo",
    category: "Especias secas",
    matchKeywords: ["cebolla en polvo"],
    priceCOP: 153200,
    unit: "kg",
    source: "Éxito.com, Cebolla Badia en polvo (78 g)",
    sourceDate: "2026-07-17",
  },
  {
    id: "pimienta-cayena",
    name: "Pimienta cayena",
    category: "Especias secas",
    matchKeywords: ["pimienta cayena"],
    priceCOP: 326600,
    unit: "kg",
    source: "Éxito.com, Pimienta Badia roja cayena (49.6 g)",
    sourceDate: "2026-07-17",
  },
  {
    id: "azafran",
    name: "Azafrán (hebras)",
    category: "Especias secas",
    matchKeywords: ["azafrán", "azafran"],
    priceCOP: 103300000,
    unit: "kg",
    source: "Éxito.com, Azafrán Carmencita en hebras (0.375 g, $38.750) -- azafrán verdadero de España; precios genéricos \"puros\" mucho más baratos en el mercado suelen ser sustitutos, no azafrán real",
    sourceDate: "2026-07-17",
  },
  {
    id: "chile-escamas",
    name: "Escamas de chile rojo",
    category: "Especias secas",
    matchKeywords: ["escamas de chile"],
    priceCOP: 250000,
    unit: "kg",
    source: "Éxito.com, Pimienta roja triturada P&I Gourmet (15 g)",
    sourceDate: "2026-07-17",
  },
  {
    id: "sal",
    name: "Sal",
    category: "Especias secas",
    matchKeywords: ["sal al gusto", "sal marina", "sal,"],
    priceCOP: 2840,
    unit: "kg",
    source: "Éxito.com, Sal Natusal marina fina (1000 g)",
    sourceDate: "2026-07-17",
  },
  {
    id: "pimienta-negra",
    name: "Pimienta negra",
    category: "Especias secas",
    matchKeywords: ["pimienta negra", "pimienta al gusto", "pimienta molida"],
    priceCOP: 199800,
    unit: "kg",
    source: "Éxito.com, Pimienta Frescampo negra entera (50 g)",
    sourceDate: "2026-07-17",
  },

  // ---- Hierbas frescas ----
  {
    id: "cilantro-fresco",
    name: "Cilantro fresco",
    category: "Hierbas frescas",
    matchKeywords: ["cilantro fresco", "cilantro o menta fresca", "cilantro o perejil fresco"],
    priceCOP: 26400,
    unit: "kg",
    isFreshHerb: true,
    source: "Éxito.com, atado de cilantro (100 g, $2.640)",
    sourceDate: "2026-07-17",
  },
  {
    id: "perejil-fresco",
    name: "Perejil fresco",
    category: "Hierbas frescas",
    matchKeywords: ["perejil fresco", "perejil o cilantro fresco"],
    priceCOP: 19000,
    unit: "kg",
    isFreshHerb: true,
    source: "Éxito.com, atado de perejil liso (100 g, $1.900)",
    sourceDate: "2026-07-17",
  },
  {
    id: "albahaca",
    name: "Albahaca fresca",
    category: "Hierbas frescas",
    matchKeywords: ["albahaca"],
    priceCOP: 44000,
    unit: "kg",
    isFreshHerb: true,
    source: "Éxito.com, capuchón de albahaca (50 g, $2.200)",
    sourceDate: "2026-07-17",
  },
  {
    id: "menta",
    name: "Menta / hierbabuena fresca",
    category: "Hierbas frescas",
    matchKeywords: ["menta fresca", "hierbabuena"],
    priceCOP: 50000,
    unit: "kg",
    isFreshHerb: true,
    source: "Estimación no verificada -- por analogía con albahaca/romero del mismo formato (capuchón ~50 g)",
    sourceDate: "2026-07-17",
  },
  {
    id: "eneldo",
    name: "Eneldo fresco",
    category: "Hierbas frescas",
    matchKeywords: ["eneldo"],
    priceCOP: 102400,
    unit: "kg",
    isFreshHerb: true,
    source: "Carulla.com, bolsa de eneldo (50 g, $5.120)",
    sourceDate: "2026-07-17",
  },
  {
    id: "romero",
    name: "Romero fresco",
    category: "Hierbas frescas",
    matchKeywords: ["romero"],
    priceCOP: 40000,
    unit: "kg",
    avgUnitWeightG: 2,
    isFreshHerb: true,
    source: "Éxito.com, capuchón de romero (50 g, $2.000)",
    sourceDate: "2026-07-17",
  },
  {
    id: "cebollin",
    name: "Cebollín / cebolla larga",
    category: "Hierbas frescas",
    matchKeywords: ["cebolla larga", "cebollín", "cebollin"],
    priceCOP: 12800,
    unit: "kg",
    avgUnitWeightG: 10,
    isFreshHerb: true,
    source: "Éxito.com, cebolla junca (500 g, $6.400)",
    sourceDate: "2026-07-17",
  },

  // ---- Vegetales y tubérculos ----
  {
    id: "cebolla-blanca",
    name: "Cebolla cabezona blanca",
    category: "Vegetales y tubérculos",
    matchKeywords: ["cebolla, ", "cebolla picada", "cebolla en trozos", "cebolla rallada", "cebolla cabezona", "cebolla en tiras", "cebolla"],
    priceCOP: 3405,
    unit: "kg",
    avgUnitWeightG: 150,
    source: "SIPSA-DANE, Boletín Semanal 717, Corabastos Bogotá (precio mayorista; el minorista es probablemente mayor)",
    sourceDate: "2026-07-10",
  },
  {
    id: "cebolla-morada",
    name: "Cebolla morada",
    category: "Vegetales y tubérculos",
    matchKeywords: ["cebolla morada"],
    priceCOP: 9664,
    unit: "kg",
    avgUnitWeightG: 120,
    source: "Éxito.com, \"Cebolla Morada Ocañera\"",
    sourceDate: "2026-07-17",
  },
  {
    id: "ajo",
    name: "Ajo",
    category: "Vegetales y tubérculos",
    matchKeywords: ["ajo picado", "ajo, picado", "dientes de ajo", "ajo rallado", "ajo en láminas", "ajo, un diente", "diente de ajo", "ajo,", "ajo"],
    priceCOP: 15556,
    unit: "kg",
    avgUnitWeightG: 5,
    source: "Éxito.com, \"Ajo del Éxito 90 g\"",
    sourceDate: "2026-07-17",
  },
  {
    id: "tomate-maduro",
    name: "Tomate maduro (chonto)",
    category: "Vegetales y tubérculos",
    matchKeywords: ["tomate maduro", "tomates maduros", "tomate picado", "tomate en cubos", "tomate triturado", "tomate, en cubos", "tomate rallado"],
    priceCOP: 5240,
    unit: "kg",
    avgUnitWeightG: 120,
    source: "Éxito.com, \"Tomate Bolsa Chonto Frescampo\"",
    sourceDate: "2026-07-17",
  },
  {
    id: "tomate-cherry",
    name: "Tomate cherry",
    category: "Vegetales y tubérculos",
    matchKeywords: ["tomate cherry", "tomates cherry"],
    priceCOP: 27800,
    unit: "kg",
    source: "Éxito.com, \"Tomate Cherry 500 g\"",
    sourceDate: "2026-07-17",
  },
  {
    id: "pimenton-rojo",
    name: "Pimentón rojo",
    category: "Vegetales y tubérculos",
    matchKeywords: ["pimentón rojo", "pimiento rojo"],
    priceCOP: 9333,
    unit: "kg",
    avgUnitWeightG: 150,
    source: "Éxito.com, \"Pimentón 1 und\" a $1.400/und, convertido con 150 g/und",
    sourceDate: "2026-07-17",
  },
  {
    id: "pimenton-verde",
    name: "Pimentón verde",
    category: "Vegetales y tubérculos",
    matchKeywords: ["pimiento verde"],
    priceCOP: 4500,
    unit: "kg",
    avgUnitWeightG: 150,
    source: "Estimación no verificada -- sin precio confirmado en fuentes consultadas",
    sourceDate: "2026-07-17",
  },
  {
    id: "pimenton-amarillo",
    name: "Pimentón amarillo",
    category: "Vegetales y tubérculos",
    matchKeywords: ["pimentón amarillo"],
    priceCOP: 8000,
    unit: "kg",
    avgUnitWeightG: 150,
    source: "Estimación no verificada -- sin precio confirmado en fuentes consultadas",
    sourceDate: "2026-07-17",
  },
  {
    id: "zanahoria",
    name: "Zanahoria",
    category: "Vegetales y tubérculos",
    matchKeywords: ["zanahoria"],
    priceCOP: 6940,
    unit: "kg",
    avgUnitWeightG: 80,
    source: "Éxito.com, \"Zanahoria Bolsa Frescampo\"",
    sourceDate: "2026-07-17",
  },
  {
    id: "calabacin",
    name: "Calabacín (zucchini)",
    category: "Vegetales y tubérculos",
    matchKeywords: ["calabacín", "calabacin"],
    priceCOP: 900,
    unit: "kg",
    avgUnitWeightG: 200,
    source: "SIPSA-DANE, Boletín Semanal 717, Corabastos Bogotá (precio mayorista; el minorista es probablemente mayor)",
    sourceDate: "2026-07-10",
  },
  {
    id: "pepino",
    name: "Pepino",
    category: "Vegetales y tubérculos",
    matchKeywords: ["pepino"],
    priceCOP: 6467,
    unit: "kg",
    avgUnitWeightG: 300,
    source: "Éxito.com, \"Pepino Cohombro 1 und\" a $1.940/und, convertido con 300 g/und",
    sourceDate: "2026-07-17",
  },
  {
    id: "apio",
    name: "Apio",
    category: "Vegetales y tubérculos",
    matchKeywords: ["apio"],
    priceCOP: 6714,
    unit: "kg",
    avgUnitWeightG: 60,
    source: "Éxito.com, \"Apio del Éxito 700 g\"",
    sourceDate: "2026-07-17",
  },
  {
    id: "brocoli",
    name: "Brócoli",
    category: "Vegetales y tubérculos",
    matchKeywords: ["brócoli", "brocoli"],
    priceCOP: 5575,
    unit: "kg",
    source: "SIPSA-DANE, Boletín Semanal 717, Corabastos Bogotá (precio mayorista)",
    sourceDate: "2026-07-10",
  },
  {
    id: "coliflor",
    name: "Coliflor",
    category: "Vegetales y tubérculos",
    matchKeywords: ["coliflor"],
    priceCOP: 2986,
    unit: "kg",
    source: "SIPSA-DANE, Boletín Semanal 717, Corabastos Bogotá (precio mayorista)",
    sourceDate: "2026-07-10",
  },
  {
    id: "espinaca",
    name: "Espinaca",
    category: "Vegetales y tubérculos",
    matchKeywords: ["espinaca"],
    priceCOP: 7520,
    unit: "kg",
    source: "Éxito.com, \"Espinaca del Éxito 300 g\"",
    sourceDate: "2026-07-17",
  },
  {
    id: "col-morada",
    name: "Col morada (repollo morado)",
    category: "Vegetales y tubérculos",
    matchKeywords: ["col morada"],
    priceCOP: 7109,
    unit: "kg",
    source: "Éxito.com, \"Repollo Morado 1 und\" a $7.820/und, convertido asumiendo cabeza de ~1.1 kg",
    sourceDate: "2026-07-17",
  },
  {
    id: "col-blanca",
    name: "Col blanca (repollo)",
    category: "Vegetales y tubérculos",
    matchKeywords: ["col blanca"],
    priceCOP: 9655,
    unit: "kg",
    source: "Éxito.com, \"Repollo Blanco 1 und\" a $10.620/und, convertido asumiendo cabeza de ~1.1 kg",
    sourceDate: "2026-07-17",
  },
  {
    id: "kale",
    name: "Col rizada (kale)",
    category: "Vegetales y tubérculos",
    matchKeywords: ["col rizada", "kale"],
    priceCOP: 112400,
    unit: "kg",
    source: "Éxito.com, \"Kale (Col Rizada) 100 g\" -- producto de especialidad, precio alto por empaque pequeño",
    sourceDate: "2026-07-17",
  },
  {
    id: "repollo-chino",
    name: "Repollo chino (napa)",
    category: "Vegetales y tubérculos",
    matchKeywords: ["repollo chino", "napa"],
    priceCOP: 6000,
    unit: "kg",
    source: "Estimación no verificada -- sin precio confirmado en fuentes consultadas",
    sourceDate: "2026-07-17",
  },
  {
    id: "lechuga",
    name: "Lechuga (crespa o romana)",
    category: "Vegetales y tubérculos",
    matchKeywords: ["lechuga"],
    priceCOP: 3500,
    unit: "unidad",
    source: "Éxito.com (varias referencias empacadas, rango $1.520-$6.540 según variedad)",
    sourceDate: "2026-07-17",
  },
  {
    id: "champinones",
    name: "Champiñones",
    category: "Vegetales y tubérculos",
    matchKeywords: ["champiñones grandes", "champiñones", "champinones"],
    priceCOP: 43040,
    unit: "kg",
    source: "Éxito.com, \"Champiñón Tajado 250 g\"",
    sourceDate: "2026-07-17",
  },
  {
    id: "champinones-shiitake",
    name: "Champiñones shiitake",
    category: "Vegetales y tubérculos",
    matchKeywords: ["shiitake"],
    priceCOP: 50000,
    unit: "kg",
    source: "Estimación no verificada -- página de producto no cargó",
    sourceDate: "2026-07-17",
  },
  {
    id: "berenjena",
    name: "Berenjena",
    category: "Vegetales y tubérculos",
    matchKeywords: ["berenjena"],
    priceCOP: 3533,
    unit: "kg",
    source: "SIPSA-DANE, Boletín Semanal 717, Corabastos Bogotá (precio mayorista)",
    sourceDate: "2026-07-10",
  },
  {
    id: "puerro",
    name: "Puerro",
    category: "Vegetales y tubérculos",
    matchKeywords: ["puerro"],
    priceCOP: 2219,
    unit: "kg",
    avgUnitWeightG: 150,
    source: "SIPSA-DANE, Boletín Semanal 717, Corabastos Bogotá (precio mayorista)",
    sourceDate: "2026-07-10",
  },
  {
    id: "ejotes",
    name: "Ejotes / habichuelas",
    category: "Vegetales y tubérculos",
    matchKeywords: ["ejotes", "habichuelas"],
    priceCOP: 10114,
    unit: "kg",
    source: "Éxito.com, \"Habichuela del Éxito 700 g\"",
    sourceDate: "2026-07-17",
  },
  {
    id: "arveja-verde",
    name: "Arveja verde",
    category: "Vegetales y tubérculos",
    matchKeywords: ["arveja verde", "arvejas verdes"],
    priceCOP: 10011,
    unit: "kg",
    source: "SIPSA-DANE, Boletín Semanal 717, Corabastos Bogotá (precio mayorista)",
    sourceDate: "2026-07-10",
  },
  {
    id: "mazorca",
    name: "Mazorca / granos de maíz tierno",
    category: "Vegetales y tubérculos",
    matchKeywords: ["granos de mazorca", "mazorca", "granos de elote"],
    priceCOP: 1290,
    unit: "kg",
    source: "SIPSA-DANE, Boletín Semanal 717, Corabastos Bogotá (precio mayorista)",
    sourceDate: "2026-07-10",
  },
  {
    id: "papa",
    name: "Papa (pastusa o sabanera)",
    category: "Vegetales y tubérculos",
    matchKeywords: ["papa sabanera", "papa,", "papa pequeña", "papa mediana"],
    priceCOP: 3072,
    unit: "kg",
    avgUnitWeightG: 150,
    source: "Éxito.com, \"Papa Pastusa Bolsa Éxito 1 kg\"",
    sourceDate: "2026-07-17",
  },
  {
    id: "papa-criolla",
    name: "Papa criolla",
    category: "Vegetales y tubérculos",
    matchKeywords: ["papa criolla"],
    priceCOP: 7760,
    unit: "kg",
    source: "Éxito.com, \"Papa Criolla del Éxito 1 kg\"",
    sourceDate: "2026-07-17",
  },
  {
    id: "camote",
    name: "Camote / batata",
    category: "Vegetales y tubérculos",
    matchKeywords: ["camote", "batata"],
    priceCOP: 6240,
    unit: "kg",
    avgUnitWeightG: 250,
    source: "Éxito.com, \"Batata 1 und\" a $1.560/und, convertido con 250 g/und",
    sourceDate: "2026-07-17",
  },
  {
    id: "calabaza",
    name: "Calabaza / auyama",
    category: "Vegetales y tubérculos",
    matchKeywords: ["calabaza", "auyama"],
    priceCOP: 2240,
    unit: "kg",
    source: "SIPSA-DANE, Boletín Semanal 717, Corabastos Bogotá (precio mayorista)",
    sourceDate: "2026-07-10",
  },
  {
    id: "aguacate",
    name: "Aguacate",
    category: "Vegetales y tubérculos",
    matchKeywords: ["aguacate"],
    priceCOP: 2000,
    unit: "unidad",
    avgUnitWeightG: 200,
    source: "Éxito.com, \"Aguacate Hass 1 und\"",
    sourceDate: "2026-07-17",
  },
  {
    id: "jengibre-fresco",
    name: "Jengibre fresco",
    category: "Vegetales y tubérculos",
    matchKeywords: ["jengibre fresco"],
    priceCOP: 160500,
    unit: "kg",
    source: "Éxito.com, \"Jengibre del Éxito 120 g\" -- empaque pequeño, precio por kg elevado",
    sourceDate: "2026-07-17",
  },
  {
    id: "chile-jalapeno",
    name: "Chile jalapeño",
    category: "Vegetales y tubérculos",
    matchKeywords: ["jalapeño", "jalapeno"],
    priceCOP: 10000,
    unit: "kg",
    source: "Estimación no verificada -- producto sin existencias en fuente consultada",
    sourceDate: "2026-07-17",
  },
  {
    id: "aji-picante",
    name: "Ají picante fresco",
    category: "Vegetales y tubérculos",
    matchKeywords: ["ají picante", "ají o chile", "chile o ají"],
    priceCOP: 12000,
    unit: "kg",
    source: "Estimación no verificada -- sin precio confirmado en fuentes consultadas",
    sourceDate: "2026-07-17",
  },
  {
    id: "edamame",
    name: "Edamame",
    category: "Vegetales y tubérculos",
    matchKeywords: ["edamame"],
    priceCOP: 17000,
    unit: "kg",
    source: "Estimación no verificada -- sin precio confirmado en fuentes consultadas",
    sourceDate: "2026-07-17",
  },
  {
    id: "bok-choy",
    name: "Bok choy",
    category: "Vegetales y tubérculos",
    matchKeywords: ["bok choy"],
    priceCOP: 10000,
    unit: "kg",
    source: "Estimación no verificada -- sin precio confirmado en fuentes consultadas",
    sourceDate: "2026-07-17",
  },
  {
    id: "esparragos",
    name: "Espárragos",
    category: "Vegetales y tubérculos",
    matchKeywords: ["espárragos", "esparragos"],
    priceCOP: 22000,
    unit: "kg",
    source: "Estimación no verificada -- fuera del alcance de esta ronda de investigación",
    sourceDate: "2026-07-17",
  },
  {
    id: "agua",
    name: "Agua",
    category: "Vegetales y tubérculos",
    matchKeywords: ["agua fría", "agua tibia", "agua (para", "agua,", "agua ", "agua"],
    priceCOP: 1,
    unit: "l",
    source: "Agua de acueducto -- costo no aplicable a efectos prácticos.",
    sourceDate: "2026-07-17",
  },

  // ---- Frutas ----
  {
    id: "limon",
    name: "Limón (Tahití)",
    category: "Frutas",
    matchKeywords: ["jugo de limón", "jugo de limon", "ralladura de limón", "limón,", "limón en", "limón ", "limón"],
    priceCOP: 5600,
    unit: "kg",
    avgUnitWeightG: 90,
    source: "Éxito.com, \"Limón Tahití Malla TAEQ 1000 g\"",
    sourceDate: "2026-07-17",
  },
  {
    id: "lima",
    name: "Lima",
    category: "Frutas",
    matchKeywords: ["lima,", "lima "],
    priceCOP: 5000,
    unit: "kg",
    avgUnitWeightG: 60,
    source: "Estimación no verificada -- sin precio diferenciado del limón Tahití en fuentes consultadas",
    sourceDate: "2026-07-17",
  },
  {
    id: "naranja",
    name: "Naranja",
    category: "Frutas",
    matchKeywords: ["naranja", "jugo de naranja"],
    priceCOP: 3136,
    unit: "kg",
    avgUnitWeightG: 200,
    source: "Éxito.com, \"Naranja Malla del Éxito 5 kg\"",
    sourceDate: "2026-07-17",
  },
  {
    id: "manzana-verde",
    name: "Manzana verde",
    category: "Frutas",
    matchKeywords: ["manzana verde", "manzanas", "manzana "],
    priceCOP: 9500,
    unit: "kg",
    avgUnitWeightG: 150,
    source: "Éxito.com, \"Manzana Verde Bolsa Insuperable TAEQ 1000 g\"",
    sourceDate: "2026-07-17",
  },
  {
    id: "platano-maduro",
    name: "Plátano maduro",
    category: "Frutas",
    matchKeywords: ["plátano maduro", "platano maduro"],
    priceCOP: 7333,
    unit: "kg",
    avgUnitWeightG: 150,
    source: "Éxito.com, \"Plátano Maduro 1 und\" a $1.100/und, convertido con 150 g/und",
    sourceDate: "2026-07-17",
  },
  {
    id: "banano",
    name: "Banano",
    category: "Frutas",
    matchKeywords: ["banano"],
    priceCOP: 3833,
    unit: "kg",
    avgUnitWeightG: 120,
    source: "Éxito.com, \"Banano 1 und\" a $460/und, convertido con 120 g/und",
    sourceDate: "2026-07-17",
  },
  {
    id: "mango",
    name: "Mango maduro",
    category: "Frutas",
    matchKeywords: ["mango maduro", "mango,"],
    priceCOP: 18743,
    unit: "kg",
    avgUnitWeightG: 350,
    source: "Éxito.com, \"Mango Tommy 1 und\" a $6.560/und, convertido con 350 g/und",
    sourceDate: "2026-07-17",
  },
  {
    id: "pina",
    name: "Piña fresca",
    category: "Frutas",
    matchKeywords: ["piña fresca", "pina fresca"],
    priceCOP: 7386,
    unit: "kg",
    avgUnitWeightG: 1400,
    source: "Éxito.com, \"Piña 1 und\" a $10.340/und, convertido asumiendo piña de ~1.4 kg",
    sourceDate: "2026-07-17",
  },
  {
    id: "peras",
    name: "Peras",
    category: "Frutas",
    matchKeywords: ["peras maduras", "peras"],
    priceCOP: 13500,
    unit: "kg",
    source: "Éxito.com, \"Pera Bolsa Frescampo 0.8 kg\"",
    sourceDate: "2026-07-17",
  },
  {
    id: "frutos-rojos",
    name: "Frutos rojos mixtos",
    category: "Frutas",
    matchKeywords: ["frutos rojos"],
    priceCOP: 38520,
    unit: "kg",
    source: "Éxito.com (promedio de fresa $32.800/kg, mora $18.440/kg, arándano $64.320/kg)",
    sourceDate: "2026-07-17",
  },

  // ---- Proteínas: carnes, pescados, huevo ----
  {
    id: "pechuga-pollo",
    name: "Pechuga de pollo",
    category: "Proteínas",
    matchKeywords: ["pechuga de pollo", "pechugas de pollo"],
    priceCOP: 20000,
    unit: "kg",
    source: "SIPSA-DANE, Corabastos (Bogotá)",
    sourceDate: "2026-01-14",
  },
  {
    id: "muslos-pollo",
    name: "Muslos / contramuslos de pollo",
    category: "Proteínas",
    matchKeywords: ["muslos de pollo", "muslos y contramuslos"],
    priceCOP: 10000,
    unit: "kg",
    source: "Estimación no verificada -- sin precio confirmado en fuentes consultadas",
    sourceDate: "2026-07-17",
  },
  {
    id: "alitas-pollo",
    name: "Alitas de pollo",
    category: "Proteínas",
    matchKeywords: ["alitas de pollo"],
    priceCOP: 9000,
    unit: "kg",
    source: "Estimación no verificada -- sin precio confirmado en fuentes consultadas",
    sourceDate: "2026-07-17",
  },
  {
    id: "pollo-hueso",
    name: "Pollo con hueso",
    category: "Proteínas",
    matchKeywords: ["piezas de pollo con hueso"],
    priceCOP: 10500,
    unit: "kg",
    source: "Estimación no verificada -- sin precio confirmado en fuentes consultadas",
    sourceDate: "2026-07-17",
  },
  {
    id: "pechuga-pavo",
    name: "Pechuga de pavo",
    category: "Proteínas",
    matchKeywords: ["pechuga de pavo", "filete de pechuga de pavo"],
    priceCOP: 48500,
    unit: "kg",
    source: "La Casa del Pavo (productor especializado)",
    sourceDate: "2026-01-01",
  },
  {
    id: "pavo-molido",
    name: "Pavo molido",
    category: "Proteínas",
    matchKeywords: ["pavo molido"],
    priceCOP: 22000,
    unit: "kg",
    source: "Estimación no verificada -- sin precio confirmado en fuentes consultadas",
    sourceDate: "2026-07-17",
  },
  {
    id: "carne-molida",
    name: "Carne de res molida",
    category: "Proteínas",
    matchKeywords: ["carne de res molida"],
    priceCOP: 20000,
    unit: "kg",
    source: "Carulla.com / Rappi (comparativa losprecios.co), rango observado $15,200-$44,400/kg según marca",
    sourceDate: "2026-07-17",
  },
  {
    id: "lomo-res",
    name: "Lomo de res",
    category: "Proteínas",
    matchKeywords: ["lomo de res"],
    priceCOP: 66340,
    unit: "kg",
    source: "SIPSA-DANE, mercado de Medellín (boletín mensual)",
    sourceDate: "2026-03-01",
  },
  {
    id: "bistec-res",
    name: "Bistec de res",
    category: "Proteínas",
    matchKeywords: ["bistec de res"],
    priceCOP: 31000,
    unit: "kg",
    source: "Estimación no verificada -- sin precio confirmado en fuentes consultadas",
    sourceDate: "2026-07-17",
  },
  {
    id: "punta-anca",
    name: "Punta de anca / falda de res",
    category: "Proteínas",
    matchKeywords: ["punta de anca", "falda de res"],
    priceCOP: 26000,
    unit: "kg",
    source: "Estimación no verificada -- SIPSA reporta variación % pero no cifra absoluta",
    sourceDate: "2026-07-17",
  },
  {
    id: "carne-estofado",
    name: "Carne de res para estofado",
    category: "Proteínas",
    matchKeywords: ["carne de res para estofado"],
    priceCOP: 20000,
    unit: "kg",
    source: "Estimación no verificada -- sin precio confirmado en fuentes consultadas",
    sourceDate: "2026-07-17",
  },
  {
    id: "lomo-cerdo",
    name: "Lomo de cerdo",
    category: "Proteínas",
    matchKeywords: ["lomo de cerdo"],
    priceCOP: 21233,
    unit: "kg",
    source: "Precio mayorista promedio nacional (prensa económica, citando datos de mercado)",
    sourceDate: "2026-04-30",
  },
  {
    id: "pescado-blanco",
    name: "Filete de pescado blanco",
    category: "Proteínas",
    matchKeywords: [
      "filete de tilapia",
      "filete de merluza",
      "lomo de bacalao",
      "filete de pescado blanco",
      "filete de mero",
      "filete de corvina",
      "filete de pescado firme",
      "pescado blanco fresco",
    ],
    priceCOP: 19076,
    unit: "kg",
    source: "SIPSA-DANE, dato nacional (tilapia como referencia)",
    sourceDate: "2026-03-24",
  },
  {
    id: "salmon",
    name: "Filete de salmón",
    category: "Proteínas",
    matchKeywords: ["filete de salmón", "filete de salmon"],
    priceCOP: 45000,
    unit: "kg",
    source: "Carulla.com / Éxito.com (promedio de listados verificados)",
    sourceDate: "2026-07-17",
  },
  {
    id: "trucha",
    name: "Filete de trucha",
    category: "Proteínas",
    matchKeywords: ["filete de trucha"],
    priceCOP: 24424,
    unit: "kg",
    source: "SIPSA-DANE, dato nacional (corte mariposa)",
    sourceDate: "2026-03-24",
  },
  {
    id: "atun-fresco",
    name: "Atún fresco (lomo)",
    category: "Proteínas",
    matchKeywords: ["lomo de atún fresco", "lomo de atun fresco"],
    priceCOP: 40000,
    unit: "kg",
    source: "Estimación no verificada -- poco común en supermercados masivos",
    sourceDate: "2026-07-17",
  },
  {
    id: "atun-lata",
    name: "Atún enlatado en agua",
    category: "Proteínas",
    matchKeywords: ["atún en agua", "atun en agua"],
    priceCOP: 6500,
    unit: "lata",
    packageSizeG: 120,
    source: "Euro Supermercados / losprecios.co (lata estándar, dentro de rango $4,490-$17,750 observado según marca; 120 g = peso neto escurrido típico)",
    sourceDate: "2026-07-17",
  },
  {
    id: "camaron",
    name: "Camarón",
    category: "Proteínas",
    matchKeywords: ["camarón", "camarones", "camaron"],
    priceCOP: 75300,
    unit: "kg",
    source: "Dato disperso de búsqueda (marca Antillana Tigre) -- confianza baja, usar con precaución",
    sourceDate: "2026-07-17",
  },
  {
    id: "mejillones",
    name: "Mejillones",
    category: "Proteínas",
    matchKeywords: ["mejillones"],
    priceCOP: 28000,
    unit: "kg",
    source: "Estimación no verificada -- producto listado sin precio confirmado",
    sourceDate: "2026-07-17",
  },
  {
    id: "pulpo",
    name: "Pulpo cocido",
    category: "Proteínas",
    matchKeywords: ["pulpo cocido"],
    priceCOP: 60000,
    unit: "kg",
    source: "Estimación no verificada -- producto listado sin precio confirmado",
    sourceDate: "2026-07-17",
  },
  {
    id: "huevo",
    name: "Huevo",
    category: "Proteínas",
    matchKeywords: ["huevo", "huevos", "claras de huevo"],
    priceCOP: 7500,
    unit: "docena",
    avgUnitWeightG: 55,
    source: "Comparativa Éxito/D1/Olímpica/Carulla (prensa económica)",
    sourceDate: "2025-12-31",
  },
  {
    id: "tofu",
    name: "Tofu firme",
    category: "Proteínas",
    matchKeywords: ["tofu firme", "tofu,"],
    priceCOP: 20000,
    unit: "kg",
    source: "Estimación no verificada -- producto listado sin precio confirmado",
    sourceDate: "2026-07-17",
  },
  {
    id: "tempeh",
    name: "Tempeh",
    category: "Proteínas",
    matchKeywords: ["tempeh"],
    priceCOP: 40000,
    unit: "kg",
    source: "Estimación no verificada -- producto de nicho, no disponible en supermercados masivos",
    sourceDate: "2026-07-17",
  },
  {
    id: "garbanzos",
    name: "Garbanzos",
    category: "Proteínas",
    matchKeywords: ["garbanzos", "garbanzo cocido"],
    priceCOP: 5900,
    unit: "kg",
    source: "Confirmado por el usuario (compra real en Colombia): $2.700-3.200 por bolsa de 500 g",
    sourceDate: "2026-07-18",
  },
  {
    id: "lentejas",
    name: "Lentejas",
    category: "Proteínas",
    matchKeywords: ["lentejas"],
    priceCOP: 5700,
    unit: "kg",
    source: "D1.com.co (marca El Estío)",
    sourceDate: "2026-07-17",
  },
  {
    id: "frijoles",
    name: "Frijoles",
    category: "Proteínas",
    matchKeywords: ["frijoles negros", "frijoles rojos", "frijol blanco", "frijol negro"],
    priceCOP: 11980,
    unit: "kg",
    source: "D1.com.co (marca El Estío, cargamanto blanco)",
    sourceDate: "2026-07-17",
  },
  {
    id: "queso-parmesano",
    name: "Queso parmesano",
    category: "Proteínas",
    matchKeywords: ["parmesano"],
    priceCOP: 85400,
    unit: "kg",
    source: "Éxito.com (Colanta)",
    sourceDate: "2026-07-17",
  },
  {
    id: "queso-feta",
    name: "Queso feta",
    category: "Proteínas",
    matchKeywords: ["queso feta"],
    priceCOP: 79600,
    unit: "kg",
    source: "Rappi/Carulla (Centurion) -- precio no confirmado por fetch directo",
    sourceDate: "2026-07-17",
  },
  {
    id: "queso-fresco",
    name: "Queso fresco / campesino",
    category: "Proteínas",
    matchKeywords: ["queso fresco"],
    priceCOP: 57600,
    unit: "kg",
    source: "Éxito.com (Alpina)",
    sourceDate: "2026-07-17",
  },
  {
    id: "queso-crema",
    name: "Queso crema",
    category: "Proteínas",
    matchKeywords: ["queso crema"],
    priceCOP: 27000,
    unit: "kg",
    source: "Estimación no verificada -- sin precio confirmado en fuentes consultadas",
    sourceDate: "2026-07-17",
  },
  {
    id: "mascarpone",
    name: "Queso mascarpone",
    category: "Proteínas",
    matchKeywords: ["mascarpone"],
    priceCOP: 52000,
    unit: "kg",
    source: "Estimación no verificada -- producto de nicho (delicatessen/importado)",
    sourceDate: "2026-07-17",
  },
  {
    id: "queso-cabra",
    name: "Queso de cabra",
    category: "Proteínas",
    matchKeywords: ["queso de cabra"],
    priceCOP: 66850,
    unit: "kg",
    source: "Carulla.com (Alcanza, tipo feta)",
    sourceDate: "2026-07-17",
  },
  {
    id: "yogur-griego",
    name: "Yogur griego natural",
    category: "Proteínas",
    matchKeywords: ["yogur griego"],
    priceCOP: 39000,
    unit: "kg",
    source: "Éxito.com (Alpina)",
    sourceDate: "2026-07-17",
  },
  {
    id: "yogur-natural",
    name: "Yogur natural",
    category: "Proteínas",
    matchKeywords: ["yogur natural"],
    priceCOP: 9000,
    unit: "kg",
    source: "Estimación no verificada -- sin precio confirmado en fuentes consultadas",
    sourceDate: "2026-07-17",
  },
  {
    id: "leche-entera",
    name: "Leche entera",
    category: "Proteínas",
    matchKeywords: ["leche entera", "leche (vegetal o entera)", "leche vegetal o entera"],
    priceCOP: 4400,
    unit: "l",
    source: "Éxito.com / D1.com.co (comparativa)",
    sourceDate: "2026-07-17",
  },
  {
    id: "leche-vegetal",
    name: "Leche vegetal",
    category: "Proteínas",
    matchKeywords: ["leche vegetal", "leche de almendra", "leche de avena"],
    priceCOP: 14000,
    unit: "l",
    source: "Estimación no verificada -- sin precio confirmado en fuentes consultadas",
    sourceDate: "2026-07-17",
  },
  {
    id: "leche-descremada",
    name: "Leche descremada",
    category: "Proteínas",
    matchKeywords: ["leche descremada"],
    priceCOP: 8380,
    unit: "l",
    source: "Éxito.com (Alpina)",
    sourceDate: "2026-07-17",
  },
  {
    id: "leche-coco",
    name: "Leche de coco",
    category: "Proteínas",
    matchKeywords: ["leche de coco"],
    priceCOP: 10000,
    unit: "lata",
    packageSizeMl: 400,
    source: "Estimación no verificada -- sin precio confirmado en fuentes consultadas",
    sourceDate: "2026-07-17",
  },

  // ---- Granos, cereales, harinas y panes ----
  {
    id: "arroz-blanco",
    name: "Arroz blanco",
    category: "Granos y harinas",
    matchKeywords: ["arroz blanco"],
    priceCOP: 3100,
    unit: "kg",
    source: "Éxito.com, Arroz Éxito Marca Propia (5000 g)",
    sourceDate: "2026-07-17",
  },
  {
    id: "arroz-integral",
    name: "Arroz integral",
    category: "Granos y harinas",
    matchKeywords: ["arroz integral", "arroz de grano corto"],
    priceCOP: 5720,
    unit: "kg",
    source: "Éxito.com, Arroz ROA integral (1000 g)",
    sourceDate: "2026-07-17",
  },
  {
    id: "arroz-basmati",
    name: "Arroz basmati",
    category: "Granos y harinas",
    matchKeywords: ["arroz basmati"],
    priceCOP: 35000,
    unit: "kg",
    source: "Éxito.com, Arroz Castellano basmati (500 g)",
    sourceDate: "2026-07-17",
  },
  {
    id: "arroz-jazmin",
    name: "Arroz jazmín",
    category: "Granos y harinas",
    matchKeywords: ["arroz jazmín", "arroz jazmin"],
    priceCOP: 28800,
    unit: "kg",
    source: "Carulla.com, Arroz Castellano jazmín (500 g)",
    sourceDate: "2026-07-17",
  },
  {
    id: "quinoa",
    name: "Quinoa",
    category: "Granos y harinas",
    matchKeywords: ["quinoa"],
    priceCOP: 48200,
    unit: "kg",
    source: "Éxito.com, Quinoa Del Alba en grano (250 g)",
    sourceDate: "2026-07-17",
  },
  {
    id: "avena",
    name: "Avena en hojuelas",
    category: "Granos y harinas",
    matchKeywords: ["avena en hojuelas", "harina de avena"],
    priceCOP: 26543,
    unit: "kg",
    source: "Éxito.com, Avena Quaker en hojuelas original (350 g)",
    sourceDate: "2026-07-17",
  },
  {
    id: "cuscus",
    name: "Cuscús integral",
    category: "Granos y harinas",
    matchKeywords: ["cuscús", "cuscus"],
    priceCOP: 11500,
    unit: "kg",
    source: "Estimación no verificada -- basada en cuscús regular Casino (500 g, $9.000/kg) + prima típica ~25-30% por versión integral",
    sourceDate: "2026-07-17",
  },
  {
    id: "pasta-integral",
    name: "Pasta integral",
    category: "Granos y harinas",
    matchKeywords: ["pasta integral", "espagueti integral"],
    priceCOP: 13840,
    unit: "kg",
    source: "Éxito.com, Pastas Doria spaghetti integral (500 g)",
    sourceDate: "2026-07-17",
  },
  {
    id: "harina-trigo",
    name: "Harina de trigo",
    category: "Granos y harinas",
    matchKeywords: ["harina de trigo", "harina integral de trigo"],
    priceCOP: 4500,
    unit: "kg",
    source: "Carulla.com, Harina de trigo Haz de Oros tradicional (500 g)",
    sourceDate: "2026-07-17",
  },
  {
    id: "harina-almendra",
    name: "Harina de almendra",
    category: "Granos y harinas",
    matchKeywords: ["harina de almendra"],
    priceCOP: 130200,
    unit: "kg",
    source: "Éxito.com, Harina Taeq de almendras (250 g)",
    sourceDate: "2026-07-17",
  },
  {
    id: "harina-garbanzo",
    name: "Harina de garbanzo",
    category: "Granos y harinas",
    matchKeywords: ["harina de garbanzo"],
    priceCOP: 25800,
    unit: "kg",
    source: "Carulla.com, Harina Taeq de garbanzo 100% natural (500 g)",
    sourceDate: "2026-07-17",
  },
  {
    id: "pan-integral",
    name: "Pan integral tajado",
    category: "Granos y harinas",
    matchKeywords: ["pan integral"],
    priceCOP: 7500,
    unit: "paquete",
    packageUnitCount: 16,
    source: "Confirmado por el usuario (compra real en Colombia): $7.500 por paquete de 520 g",
    sourceDate: "2026-07-18",
  },
  {
    id: "pan-rallado",
    name: "Pan rallado",
    category: "Granos y harinas",
    matchKeywords: ["pan rallado"],
    priceCOP: 44200,
    unit: "kg",
    source: "Éxito.com, Pan rallado Best Choice estilo oriental (200 g, $8.840)",
    sourceDate: "2026-07-17",
  },
  {
    id: "tortillas-maiz",
    name: "Tortillas de maíz",
    category: "Granos y harinas",
    matchKeywords: ["tortillas de maíz", "tortillas de maiz"],
    priceCOP: 8440,
    unit: "paquete",
    packageUnitCount: 12,
    source: "Éxito.com, Tortillas Sary de maíz sin gluten (240 g, x12 und)",
    sourceDate: "2026-07-17",
  },
  {
    id: "tortillas-integrales",
    name: "Tortillas integrales",
    category: "Granos y harinas",
    matchKeywords: ["tortillas integrales"],
    priceCOP: 7950,
    unit: "paquete",
    packageUnitCount: 8,
    source: "Éxito.com, Tortillas Taeq de harina de trigo integral (250 g)",
    sourceDate: "2026-07-17",
  },
  {
    id: "papel-arroz",
    name: "Papel de arroz",
    category: "Granos y harinas",
    matchKeywords: ["papel de arroz"],
    priceCOP: 24000,
    unit: "paquete",
    packageUnitCount: 50,
    source: "Carulla.com, Papel de arroz Best Choice pasta de arroz (300 g)",
    sourceDate: "2026-07-17",
  },
  {
    id: "fideos-arroz",
    name: "Fideos de arroz",
    category: "Granos y harinas",
    matchKeywords: ["fideos de arroz"],
    priceCOP: 40900,
    unit: "kg",
    source: "Éxito.com, Pastas Doria vermicelli sin gluten de arroz (200 g)",
    sourceDate: "2026-07-17",
  },
  {
    id: "galletas-integrales",
    name: "Galletas integrales",
    category: "Granos y harinas",
    matchKeywords: ["galletas integrales"],
    priceCOP: 6370,
    unit: "paquete",
    packageSizeG: 220,
    source: "Éxito.com, Galletas Saltinas integrales (220.5 g)",
    sourceDate: "2026-07-17",
  },
  {
    id: "bizcochos-soletilla",
    name: "Bizcochos de soletilla",
    category: "Granos y harinas",
    matchKeywords: ["bizcochos de soletilla"],
    priceCOP: 15100,
    unit: "paquete",
    packageSizeG: 200,
    source: "Éxito.com, Bizcochos Gastone Lago Elledi de soletilla (200 g, ítem de importación)",
    sourceDate: "2026-07-17",
  },

  // ---- Endulzantes y chocolate ----
  {
    id: "miel",
    name: "Miel",
    category: "Endulzantes",
    matchKeywords: ["miel"],
    priceCOP: 49700,
    unit: "kg",
    source: "Éxito.com, Miel Del Néctar natural (350 g)",
    sourceDate: "2026-07-17",
  },
  {
    id: "panela",
    name: "Panela raspada / azúcar de coco",
    category: "Endulzantes",
    matchKeywords: ["panela raspada", "azúcar de coco"],
    priceCOP: 13900,
    unit: "kg",
    source: "Éxito.com, Panela Doña Panela pulverizada (500 g). Nota: el azúcar de coco es un producto mucho más caro (~$207.000/kg, Éxito.com A De Coco) -- se usa panela como referencia por ser la opción más común cuando la receta ofrece ambas como alternativa",
    sourceDate: "2026-07-17",
  },
  {
    id: "chocolate-oscuro",
    name: "Chocolate oscuro 70%",
    category: "Endulzantes",
    matchKeywords: ["chocolate oscuro"],
    priceCOP: 398300,
    unit: "kg",
    source: "Éxito.com, Chocolate Santander amargo 70% cacao (700 g)",
    sourceDate: "2026-07-17",
  },
  {
    id: "cacao-polvo",
    name: "Cacao en polvo sin azúcar",
    category: "Endulzantes",
    matchKeywords: ["cacao en polvo"],
    priceCOP: 91750,
    unit: "kg",
    source: "Éxito.com, Cacao Tosh en polvo (200 g)",
    sourceDate: "2026-07-17",
  },
  {
    id: "datiles",
    name: "Dátiles deshuesados",
    category: "Endulzantes",
    matchKeywords: ["dátiles", "datiles"],
    priceCOP: 116700,
    unit: "kg",
    source: "Éxito.com, Dátiles sin marca (300 g)",
    sourceDate: "2026-07-17",
  },
  {
    id: "pasas",
    name: "Pasas",
    category: "Endulzantes",
    matchKeywords: ["pasas"],
    priceCOP: 30450,
    unit: "kg",
    source: "Éxito.com, Uvas pasas Frescampo deshidratadas (200 g)",
    sourceDate: "2026-07-17",
  },
  {
    id: "arandanos-deshidratados",
    name: "Arándanos deshidratados",
    category: "Endulzantes",
    matchKeywords: ["arándanos deshidratados", "arandanos deshidratados"],
    priceCOP: 68000,
    unit: "kg",
    source: "Éxito.com, Arándanos Doña Betty deshidratados (200 g)",
    sourceDate: "2026-07-17",
  },
  {
    id: "azucar",
    name: "Azúcar",
    category: "Endulzantes",
    matchKeywords: ["azúcar o panela", "azúcar,", "azucar"],
    priceCOP: 5100,
    unit: "kg",
    source: "Éxito.com, Azúcar Riopaila blanca (1000 g)",
    sourceDate: "2026-07-17",
  },

  // ---- Salsas, caldos, vinagres y encurtidos ----
  {
    id: "salsa-soya",
    name: "Salsa de soya",
    category: "Salsas y caldos",
    matchKeywords: ["salsa de soya", "tamari"],
    priceCOP: 31900,
    unit: "l",
    source: "Éxito.com, Salsa soya Sakura reducida en sodio (500 ml)",
    sourceDate: "2026-07-17",
  },
  {
    id: "caldo-vegetales",
    name: "Caldo de vegetales",
    category: "Salsas y caldos",
    matchKeywords: ["caldo de vegetales"],
    priceCOP: 350,
    unit: "l",
    source: "Estimación no verificada -- sin SKU vigente en Éxito/Carulla/Jumbo; estimado por analogía con cubos de pollo/res reconstituidos (~1 cubo = 1 L de caldo preparado)",
    sourceDate: "2026-07-17",
  },
  {
    id: "caldo-pollo",
    name: "Caldo de pollo",
    category: "Salsas y caldos",
    matchKeywords: ["caldo de pollo"],
    priceCOP: 300,
    unit: "l",
    source: "Éxito.com, Caldo de gallina Frescampo criolla (8 cubos/92 g, $2.260), convertido asumiendo 1 cubo = 1 L de caldo preparado. La versión baja en sodio no tiene SKU vigente; se usa la regular como referencia",
    sourceDate: "2026-07-17",
  },
  {
    id: "caldo-res",
    name: "Caldo de res",
    category: "Salsas y caldos",
    matchKeywords: ["caldo de res"],
    priceCOP: 270,
    unit: "l",
    source: "Éxito.com, Caldo de costilla Frescampo (8 cubos/92 g, $1.970), convertido asumiendo 1 cubo = 1 L de caldo preparado. La versión baja en sodio no tiene SKU vigente; se usa la regular como referencia",
    sourceDate: "2026-07-17",
  },
  {
    id: "caldo-pescado",
    name: "Caldo de pescado o mariscos",
    category: "Salsas y caldos",
    matchKeywords: ["caldo de pescado", "caldo de mariscos"],
    priceCOP: 950,
    unit: "l",
    source: "Éxito.com, Caldo de Pescado P.J Pesquera Jaramillo (80 g, $6.600), convertido con el mismo rendimiento que los cubos de pollo/res (~11.5 g por litro de caldo preparado)",
    sourceDate: "2026-07-17",
  },
  {
    id: "vino-blanco",
    name: "Vino blanco seco",
    category: "Salsas y caldos",
    matchKeywords: ["vino blanco"],
    priceCOP: 35764,
    unit: "l",
    source: "Éxito.com, Vino blanco Grajales de cocina (275 ml)",
    sourceDate: "2026-07-17",
  },
  {
    id: "vinagre-arroz",
    name: "Vinagre de arroz",
    category: "Salsas y caldos",
    matchKeywords: ["vinagre de arroz"],
    priceCOP: 25000,
    unit: "l",
    source: "Éxito.com, Vinagre de vino y arroz Chang & Chan (480 ml)",
    sourceDate: "2026-07-17",
  },
  {
    id: "vinagre-tinto",
    name: "Vinagre de vino tinto",
    category: "Salsas y caldos",
    matchKeywords: ["vinagre de vino tinto"],
    priceCOP: 34500,
    unit: "l",
    source: "Éxito.com, Vinagre de vino tinto Colavita (500 ml)",
    sourceDate: "2026-07-17",
  },
  {
    id: "vinagre-balsamico",
    name: "Vinagre balsámico",
    category: "Salsas y caldos",
    matchKeywords: ["vinagre balsámico", "vinagre balsamico"],
    priceCOP: 49950,
    unit: "l",
    source: "Éxito.com, Vinagre balsámico La Coruna (200 ml)",
    sourceDate: "2026-07-17",
  },
  {
    id: "vinagre-manzana",
    name: "Vinagre de manzana",
    category: "Salsas y caldos",
    matchKeywords: ["vinagre de manzana"],
    priceCOP: 8840,
    unit: "l",
    source: "Éxito.com, Vinagre de manzana Barrentos especial (500 ml)",
    sourceDate: "2026-07-17",
  },
  {
    id: "vinagre-blanco",
    name: "Vinagre blanco",
    category: "Salsas y caldos",
    matchKeywords: ["vinagre blanco", "vinagre de vino blanco"],
    priceCOP: 5500,
    unit: "l",
    source: "Éxito.com, Vinagre blanco Barrentos multiusos (500 ml)",
    sourceDate: "2026-07-17",
  },
  {
    id: "mostaza-dijon",
    name: "Mostaza dijon",
    category: "Salsas y caldos",
    matchKeywords: ["mostaza dijon"],
    priceCOP: 40882,
    unit: "kg",
    source: "Éxito.com, Mostaza Kari Dijon (340 g)",
    sourceDate: "2026-07-17",
  },
  {
    id: "tahini",
    name: "Tahini",
    category: "Salsas y caldos",
    matchKeywords: ["tahini"],
    priceCOP: 64375,
    unit: "kg",
    source: "Éxito.com, Pasta de ajonjolí Tahini Al Fresco (240 g)",
    sourceDate: "2026-07-17",
  },
  {
    id: "hummus",
    name: "Hummus",
    category: "Salsas y caldos",
    matchKeywords: ["hummus"],
    priceCOP: 124884,
    unit: "kg",
    source: "Éxito.com, Crema garbanzo tahini hummus clásico Mezete (215 g)",
    sourceDate: "2026-07-17",
  },
  {
    id: "salsa-pescado",
    name: "Salsa de pescado",
    category: "Salsas y caldos",
    matchKeywords: ["salsa de pescado"],
    priceCOP: 37000,
    unit: "l",
    source: "Éxito.com, Salsa de pescado Best Choice tailandesa (700 ml)",
    sourceDate: "2026-07-17",
  },
  {
    id: "salsa-ostion",
    name: "Salsa de ostión",
    category: "Salsas y caldos",
    matchKeywords: ["salsa de ostión", "salsa de ostion"],
    priceCOP: 103529,
    unit: "l",
    source: "Carulla.com, Salsa de ostras Lee Kum Kee (255 g), tratado como ~1 g/ml",
    sourceDate: "2026-07-17",
  },
  {
    id: "pasta-curry",
    name: "Pasta de curry",
    category: "Salsas y caldos",
    matchKeywords: ["pasta de curry"],
    priceCOP: 140000,
    unit: "kg",
    source: "Estimación no verificada -- Thai Kitchen/Mae Ploy/Patak's figuran en catálogo sin precio vigente",
    sourceDate: "2026-07-17",
  },
  {
    id: "pasta-miso",
    name: "Pasta de miso blanco",
    category: "Salsas y caldos",
    matchKeywords: ["pasta de miso"],
    priceCOP: 90000,
    unit: "kg",
    source: "Estimación no verificada -- no está en catálogo mainstream, típico de tienda asiática especializada",
    sourceDate: "2026-07-17",
  },
  {
    id: "alga-wakame",
    name: "Alga wakame seca",
    category: "Salsas y caldos",
    matchKeywords: ["alga wakame"],
    priceCOP: 25000,
    unit: "paquete",
    packageSizeG: 50,
    source: "Estimación no verificada -- no está en catálogo mainstream, típico de tienda asiática especializada",
    sourceDate: "2026-07-17",
  },
  {
    id: "pasta-achiote",
    name: "Pasta de achiote",
    category: "Salsas y caldos",
    matchKeywords: ["pasta de achiote"],
    priceCOP: 18000,
    unit: "kg",
    source: "Éxito.com, \"Color con achiote\" El Cocinerito (100 g) -- condimento/colorante de achiote, el equivalente real más cercano disponible en supermercado; pasta pura importada podría costar más",
    sourceDate: "2026-07-17",
  },
  {
    id: "sriracha",
    name: "Sriracha / salsa picante",
    category: "Salsas y caldos",
    matchKeywords: ["sriracha", "salsa picante"],
    priceCOP: 21550,
    unit: "botella",
    packageSizeMl: 250,
    source: "Éxito.com, Salsa Kari Sriracha Chili Gourmet (250 ml)",
    sourceDate: "2026-07-17",
  },
  {
    id: "aceitunas-negras",
    name: "Aceitunas negras",
    category: "Salsas y caldos",
    matchKeywords: ["aceitunas negras"],
    priceCOP: 49643,
    unit: "kg",
    source: "Éxito.com, Aceitunas Al Fresco negras enteras (280 g)",
    sourceDate: "2026-07-17",
  },
  {
    id: "aceitunas-verdes",
    name: "Aceitunas verdes",
    category: "Salsas y caldos",
    matchKeywords: ["aceitunas verdes"],
    priceCOP: 42000,
    unit: "kg",
    source: "Éxito.com, Aceitunas Al Fresco verdes enteras manzanilla (140 g)",
    sourceDate: "2026-07-17",
  },
  {
    id: "alcaparras",
    name: "Alcaparras",
    category: "Salsas y caldos",
    matchKeywords: ["alcaparras"],
    priceCOP: 64692,
    unit: "kg",
    source: "Éxito.com, Alcaparras La Coruna en vinagre (130 g)",
    sourceDate: "2026-07-17",
  },
  {
    id: "anchoas",
    name: "Filetes de anchoa",
    category: "Salsas y caldos",
    matchKeywords: ["anchoa"],
    priceCOP: 9000,
    unit: "lata",
    packageSizeG: 56,
    source: "Estimación no verificada -- único listado (Sabores de Colombia Rubias, 56 g) sin precio vigente",
    sourceDate: "2026-07-17",
  },
  {
    id: "palmitos",
    name: "Palmitos en conserva",
    category: "Salsas y caldos",
    matchKeywords: ["palmitos"],
    priceCOP: 12550,
    unit: "lata",
    packageSizeG: 220,
    source: "Éxito.com, Palmitos del Putumayo en conserva sin sal (220 g)",
    sourceDate: "2026-07-17",
  },
  {
    id: "tomate-lata",
    name: "Tomate triturado enlatado",
    category: "Salsas y caldos",
    matchKeywords: ["tomate en cubos (enlatado", "tomate triturado (lata)", "pasta de tomate"],
    priceCOP: 5450,
    unit: "lata",
    packageSizeG: 240,
    packageSizeMl: 240,
    source: "Éxito.com, Tomate To Eat Marca Exclusiva enlatado (240 g); tratado como ~1 g/ml para medidas en cucharadas de pasta de tomate",
    sourceDate: "2026-07-17",
  },

  // ---- Frutos secos y semillas ----
  {
    id: "nueces",
    name: "Nueces",
    category: "Frutos secos y semillas",
    matchKeywords: ["nueces", "frutos secos picados"],
    priceCOP: 144000,
    unit: "kg",
    source: "Éxito.com, Nueces El Nogal partidas (200 g)",
    sourceDate: "2026-07-17",
  },
  {
    id: "almendras",
    name: "Almendras",
    category: "Frutos secos y semillas",
    matchKeywords: ["almendras"],
    priceCOP: 69800,
    unit: "kg",
    source: "Éxito.com, Almendras Green Republic Foods naturales (500 g)",
    sourceDate: "2026-07-17",
  },
  {
    id: "mani-tostado",
    name: "Maní tostado",
    category: "Frutos secos y semillas",
    matchKeywords: ["maní tostado", "mani tostado"],
    priceCOP: 39900,
    unit: "kg",
    source: "Éxito.com, Maní salado (1000 g)",
    sourceDate: "2026-07-17",
  },
  {
    id: "mantequilla-mani",
    name: "Mantequilla de maní",
    category: "Frutos secos y semillas",
    matchKeywords: ["mantequilla de maní", "mantequilla de mani"],
    priceCOP: 44500,
    unit: "kg",
    source: "Éxito.com, Crema de maní Taeq 100% natural (300 g)",
    sourceDate: "2026-07-17",
  },
  {
    id: "ajonjoli",
    name: "Semillas de ajonjolí / sésamo",
    category: "Frutos secos y semillas",
    matchKeywords: ["ajonjolí", "ajonjoli", "semillas de sésamo", "semillas de sesamo"],
    priceCOP: 74500,
    unit: "kg",
    source: "Éxito.com, Semillas de ajonjolí Del Alba (200 g)",
    sourceDate: "2026-07-17",
  },
  {
    id: "chia",
    name: "Semillas de chía",
    category: "Frutos secos y semillas",
    matchKeywords: ["semillas de chía", "semillas de chia"],
    priceCOP: 94500,
    unit: "kg",
    source: "Éxito.com, Semillas de chía Del Alba (200 g)",
    sourceDate: "2026-07-17",
  },
  {
    id: "girasol",
    name: "Semillas de girasol",
    category: "Frutos secos y semillas",
    matchKeywords: ["semillas de girasol"],
    priceCOP: 45300,
    unit: "kg",
    source: "Carulla.com, Semillas de girasol Insualimentos (150 g)",
    sourceDate: "2026-07-17",
  },
  {
    id: "semillas-calabaza",
    name: "Semillas de calabaza tostadas",
    category: "Frutos secos y semillas",
    matchKeywords: ["semillas de calabaza"],
    priceCOP: 72300,
    unit: "kg",
    source: "Carulla.com, Semillas de calabaza Insualimentos (150 g, versión cruda usada como proxy de la tostada)",
    sourceDate: "2026-07-17",
  },

  // ---- Despensa y otros ----
  {
    id: "gelatina-sin-sabor",
    name: "Gelatina sin sabor en polvo",
    category: "Despensa y otros",
    matchKeywords: ["gelatina sin sabor"],
    priceCOP: 2820,
    unit: "caja",
    packageSizeG: 30,
    source: "Éxito.com, Gelatina Frutino sin sabor (30 g)",
    sourceDate: "2026-07-17",
  },
  {
    id: "polvo-hornear",
    name: "Polvo de hornear",
    category: "Despensa y otros",
    matchKeywords: ["polvo de hornear"],
    priceCOP: 112375,
    unit: "kg",
    source: "Éxito.com, Polvo para hornear Levapan (80 g, $8.990)",
    sourceDate: "2026-07-17",
  },
  {
    id: "bicarbonato",
    name: "Bicarbonato de sodio",
    category: "Despensa y otros",
    matchKeywords: ["bicarbonato de sodio"],
    priceCOP: 7560,
    unit: "kg",
    source: "Éxito.com, Bicarbonato Frescampo de sodio (500 g)",
    sourceDate: "2026-07-17",
  },
  {
    id: "maicena",
    name: "Maicena / fécula de maíz",
    category: "Despensa y otros",
    matchKeywords: ["maicena", "fécula de maíz", "fecula de maiz"],
    priceCOP: 40263,
    unit: "kg",
    source: "Carulla.com, Fécula Maizena de maíz (380 g)",
    sourceDate: "2026-07-17",
  },
  {
    id: "cafe-instantaneo",
    name: "Café instantáneo",
    category: "Despensa y otros",
    matchKeywords: ["café instantáneo", "cafe instantaneo"],
    priceCOP: 102235,
    unit: "kg",
    source: "Éxito.com, Café Frescampo instantáneo (85 g) -- opción económica; Nescafé Tradición llega a $230.000/kg",
    sourceDate: "2026-07-17",
  },
  {
    id: "cafe-espresso",
    name: "Café espresso",
    category: "Despensa y otros",
    matchKeywords: ["café espresso", "cafe espresso"],
    priceCOP: 120000,
    unit: "kg",
    source: "Estimación no verificada -- fuera del alcance de esta ronda de investigación",
    sourceDate: "2026-07-17",
  },
  {
    id: "esencia-vainilla",
    name: "Esencia de vainilla",
    category: "Despensa y otros",
    matchKeywords: ["esencia de vainilla"],
    priceCOP: 15000,
    unit: "botella",
    packageSizeMl: 30,
    source: "Estimación no verificada -- fuera del alcance de esta ronda de investigación",
    sourceDate: "2026-07-17",
  },
];
